SELECT
  assessment_id,
  answers -> 'sipindustryprogramsAllianceforWatertime' AS AllianceforWater, 
  answers -> 'sipindustryprogramsAiiCarbonLeadershiptime' AS AiiCarbonLeadershiptime,
  answers -> 'sipindustryprogramsAiiCleanbyDesigntime' AS AiiCleanbyDesigntime,
  answers -> 'sipindustryprogramsAiiCleanbyDesignPlustime' AS AiiCleanbyDesignPlustime,
  answers -> 'sipindustryprogramsAiiCleanbyDesignChemistrytime' AS AiiCleanbyDesignChemistrytime,
  answers -> 'sipindustryprogramsAiiCleanbyDesignTier1time' AS AiiCleanbyDesignTier1time,
  answers -> 'sipindustryprogramsAiiCoalPhaseOuttime' AS AiiCoalPhaseOuttime,
  answers -> 'sipindustryprogramsAiiRenewableEnergytime' AS AiiRenewableEnergytime,
  answers -> 'sipindustryprogramsbreeamtime' AS breeamtime,
  answers -> 'sipindustryprogramsbveenvironmentalemissionevaluatortime' AS bveenvironmentalemissionevaluatortime,
  answers -> 'sipindustryprogramscountryspecificgreenbuildingcertificationtime' AS countryspecificgreenbuildingcertificationtime,
  answers -> 'sipindustryprogramsCradletoCradletime' AS CradletoCradletime,
  answers -> 'sipindustryprogramsEMAStime' AS EMAStime,
  answers -> 'sipindustryprogramsFairWeartime' AS FairWeartime,
  answers -> 'sipindustryprogramsFashionforGoodtime' AS FashionforGoodtime,
  answers -> 'sipindustryprogramsFSCtime' AS FSCtime,
  answers -> 'sipindustryprogramsGOTStime' AS GOTStime,
  answers -> 'sipindustryprogramsIDHtime' AS IDHtime,
  answers -> 'sipindustryprogramsIFCtime' AS IFCtime,
  answers -> 'sipindustryprogramsIPEtime' AS IPEtime,
  answers -> 'sipindustryprogramsISO14001time' AS ISO14001time,
  answers -> 'sipindustryprogramsisopreviouslyknownasohsastime' AS isopreviouslyknownasohsastime,
  answers -> 'sipindustryprogramsISO50001time' AS ISO50001time,
  answers -> 'sipindustryprogramsITCtime' AS ITCtime,
  answers -> 'sipindustryprogramsISCtime' AS ISCtime,
  answers -> 'sipindustryprogramsleedtime' AS leedtime,
  answers -> 'sipindustryprogramsLWGtime' AS LWGtime,
  answers -> 'sipindustryprogramsOekoTexMadeinGreentime' AS OekoTexMadeinGreentime,
  answers -> 'sipindustryprogramsOekoTexSTePtime' AS OekoTexSTePtime,
  answers -> 'sipindustryprogramsVAPtime' AS VAPtime,
  answers -> 'sipindustryprogramsRSPOtime' AS RSPOtime,
  answers -> 'sipindustryprogramsScienceBasedTargettime' AS ScienceBasedTargettime,
  answers -> 'sipindustryprogramsTEGlobalREcycledtime' AS TEGlobalREcycledtime,
  answers -> 'sipindustryprogramsTEOrganicContenttime' AS TEOrganicContenttime,
  answers -> 'sipindustryprogramsTEResponsibleDowntime' AS TEResponsibleDowntime,
  answers -> 'sipindustryprogramsTEResponsibleWooltime' AS TEResponsibleWooltime,
  answers -> 'sipindustryprogramsTERecycledContenttime' AS TERecycledContenttime,
  answers -> 'sipindustryprogramsZDHCChemicalsGatewaytime' AS ZDHCChemicalsGatewaytime,
  answers -> 'sipindustryprogramsZDHCWastewatertime' AS ZDHCWastewatertime,
  answers -> 'sipindustryprogramsZDHCSuppliertoZerotime' AS ZDHCSuppliertoZerotime,
  answers -> 'sipindustryprogramsothertime' AS othertime,
  answers -> 'sipindustryprogramsBEPItime' AS BEPItime,
  answers -> 'sipindustryprogramsBluesigntime' AS Bluesigntime
FROM public.fem_simple
WHERE rfi_pid = 'fem2024'
  AND facility_posted = true
  AND status != 'ASD'
LIMIT 1000