with fslm_cte AS(
SELECT 
    fslm.assessment_id,
    fslm.account_id,
    fslm.survey_version,
    (fslm.performance ->> 'cl_age_verification')::text AS cl_age_verification,
    (fslm.performance ->> 'cl_hazardous_work_legal')::boolean AS cl_hazardous_work_legal,
    (fslm.performance ->> 'cl_healthchecks')::text AS cl_healthchecks,
    (fslm.performance ->> 'cl_healthchecks_legal')::text AS cl_healthchecks_legal,
    (fslm.performance ->> 'cl_hs_protective_restrictions')::text AS cl_hs_protective_restrictions,
    (fslm.performance ->> 'cl_hs_separate_trainings')::text AS cl_hs_separate_trainings,
    (fslm.performance ->> 'cl_hs_specialtrainings')::text AS cl_hs_specialtrainings,
    (fslm.performance ->> 'cl_implement_separate_tracking')::text AS cl_implement_separate_tracking,
    (fslm.performance ->> 'cl_internship_legal')::text AS cl_internship_legal,
    (fslm.performance ->> 'cl_nightwork')::boolean AS cl_nightwork,
    (fslm.performance ->> 'cl_parental_permission')::text AS cl_parental_permission,
    (fslm.performance ->> 'cl_parental_review')::text AS cl_parental_review,
    (fslm.performance ->> 'cl_protectiverestriction_u18')::text AS cl_protectiverestriction_u18,
    (fslm.performance ->> 'cl_written_remediation_policy')::text AS cl_written_remediation_policy,
    (fslm.performance ->> 'cl_youngest_worker')::text AS cl_youngest_worker,
    (fslm.performance ->> 'disc_contraception_hiring')::boolean AS disc_contraception_hiring,
    (fslm.performance ->> 'disc_contraception_requirement_employment')::boolean AS disc_contraception_requirement_employment,
    (fslm.performance ->> 'disc_disabled_hiring_legal')::text AS disc_disabled_hiring_legal,
    (fslm.performance ->> 'disc_illness_termination')::text AS disc_illness_termination,
    (fslm.performance ->> 'disc_pregnancy_requirements_hiring')::boolean AS disc_pregnancy_requirements_hiring,
    (fslm.performance ->> 'disc_promotion_age')::boolean AS disc_promotion_age,
    (fslm.performance ->> 'disc_promotion_disability')::boolean AS disc_promotion_disability,
    (fslm.performance ->> 'disc_promotion_hiv')::boolean AS disc_promotion_hiv,
    (fslm.performance ->> 'disc_promotion_maritalstatus')::boolean AS disc_promotion_maritalstatus,
    (fslm.performance ->> 'disc_promotion_maternity')::boolean AS disc_promotion_maternity,
    (fslm.performance ->> 'disc_promotion_nationalextraction')::boolean AS disc_promotion_nationalextraction,
    (fslm.performance ->> 'disc_promotion_nationality')::boolean AS disc_promotion_nationality,
    (fslm.performance ->> 'disc_promotion_other')::boolean AS disc_promotion_other,
    (fslm.performance ->> 'disc_promotion_politicalopinion')::boolean AS disc_promotion_politicalopinion,
    (fslm.performance ->> 'disc_promotion_race')::boolean AS disc_promotion_race,
    (fslm.performance ->> 'disc_promotion_religion')::boolean AS disc_promotion_religion,
    (fslm.performance ->> 'disc_promotion_sex')::boolean AS disc_promotion_sex,
    (fslm.performance ->> 'disc_promotion_sexualorientation')::boolean AS disc_promotion_sexualorientation,
    (fslm.performance ->> 'disc_promotion_socialorigin')::boolean AS disc_promotion_socialorigin,
    (fslm.performance ->> 'disc_retaliation_termination')::text AS disc_retaliation_termination,
    (fslm.performance ->> 'disc_termination_age')::boolean AS disc_termination_age,
    (fslm.performance ->> 'disc_termination_disability')::boolean AS disc_termination_disability,
    (fslm.performance ->> 'disc_termination_hiv')::boolean AS disc_termination_hiv,
    (fslm.performance ->> 'disc_termination_maritalstatus')::boolean AS disc_termination_maritalstatus,
    (fslm.performance ->> 'disc_termination_maternity')::boolean AS disc_termination_maternity,
    (fslm.performance ->> 'disc_termination_nationalextraction')::boolean AS disc_termination_nationalextraction,
    (fslm.performance ->> 'disc_termination_nationality')::boolean AS disc_termination_nationality,
    (fslm.performance ->> 'disc_termination_other')::boolean AS disc_termination_other,
    (fslm.performance ->> 'disc_termination_politicalopinion')::boolean AS disc_termination_politicalopinion,
    (fslm.performance ->> 'disc_termination_race')::boolean AS disc_termination_race,
    (fslm.performance ->> 'disc_termination_religion')::boolean AS disc_termination_religion,
    (fslm.performance ->> 'disc_termination_sex')::boolean AS disc_termination_sex,
    (fslm.performance ->> 'disc_termination_sexualorientation')::boolean AS disc_termination_sexualorientation,
    (fslm.performance ->> 'disc_termination_socialorigin')::boolean AS disc_termination_socialorigin,
    (fslm.performance ->> 'disc_virginity_test_hiring')::boolean AS disc_virginity_test_hiring,
    (fslm.performance ->> 'discp_legal')::text AS discp_legal,
    (fslm.performance ->> 'ep_defense')::text AS ep_defense,
    (fslm.performance ->> 'ep_limits_fixed_contracts')::text AS ep_limits_fixed_contracts,
    (fslm.performance ->> 'ep_personnelfiles_legal')::text AS ep_personnelfiles_legal,
    (fslm.performance ->> 'ep_probation_legal')::text AS ep_probation_legal,
    (fslm.performance ->> 'ep_rif_alternatives')::text AS ep_rif_alternatives,
    (fslm.performance ->> 'ep_temp_contracts_avoid_legal')::text AS ep_temp_contracts_avoid_legal,
    (fslm.performance ->> 'ep_work_legal')::text AS ep_work_legal,
    (fslm.performance ->> 'ep_workers_were_not_given_notice')::text AS ep_workers_were_not_given_notice,
    (fslm.performance ->> 'erg_retaliation')::text AS erg_retaliation,
    (fslm.performance ->> 'fl_forced_overtime')::text AS fl_forced_overtime,
    (fslm.performance ->> 'fl_migrant_recruitment_legal')::text AS fl_migrant_recruitment_legal,
    (fslm.performance ->> 'fl_passport_access')::text AS fl_passport_access,
    (fslm.performance ->> 'fl_prison_labor')::text AS fl_prison_labor,
    (fslm.performance ->> 'fl_recruitment_costs_legal')::text AS fl_recruitment_costs_legal,
    (fslm.performance ->> 'fl_reimbursement_fees')::text AS fl_reimbursement_fees,
    (fslm.performance ->> 'fl_restricted_leaving')::text AS fl_restricted_leaving,
    (fslm.performance ->> 'fl_terminate_employment_postnotice')::text AS fl_terminate_employment_postnotice,
    (fslm.performance ->> 'fl_witheld_payments')::text AS fl_witheld_payments,
    (fslm.performance ->> 'foa_armed_break_strike')::boolean AS foa_armed_break_strike,
    (fslm.performance ->> 'foa_cba_favorable_as_law')::text AS foa_cba_favorable_as_law,
    (fslm.performance ->> 'foa_consultation_union_legal')::text AS foa_consultation_union_legal,
    (fslm.performance ->> 'foa_control_unions')::text AS foa_control_unions,
    (fslm.performance ->> 'foa_equal_union_treatment_legal')::text AS foa_equal_union_treatment_legal,
    (fslm.performance ->> 'foa_form_join_federations')::text AS foa_form_join_federations,
    (fslm.performance ->> 'foa_free_to_meet_wo_mgmt')::text AS foa_free_to_meet_wo_mgmt,
    (fslm.performance ->> 'foa_new_workers_replace_strikers')::boolean AS foa_new_workers_replace_strikers,
    (fslm.performance ->> 'foa_private_meeting_legal')::text AS foa_private_meeting_legal,
    (fslm.performance ->> 'foa_punished_strikes')::boolean AS foa_punished_strikes,
    (fslm.performance ->> 'foa_required_union')::text AS foa_required_union,
    (fslm.performance ->> 'foa_trade_union_representatives_access')::text AS foa_trade_union_representatives_access,
    (fslm.performance ->> 'foa_union_activity_hiring')::text AS foa_union_activity_hiring,
    (fslm.performance ->> 'foa_union_intimidation')::boolean AS foa_union_intimidation,
    (fslm.performance ->> 'foa_union_punished')::boolean AS foa_union_punished,
    (fslm.performance ->> 'foa_union_support_legal')::text AS foa_union_support_legal,
    (fslm.performance ->> 'foa_union_terminated')::boolean AS foa_union_terminated,
    (fslm.performance ->> 'foa_unions')::text AS foa_unions,
    (fslm.performance ->> 'foa_untion_deductions_legal')::text AS foa_untion_deductions_legal,
    (fslm.performance ->> 'hb_cases_abuse')::text AS hb_cases_abuse,
    (fslm.performance ->> 'hb_cases_characteristics')::text AS hb_cases_characteristics,
    (fslm.performance ->> 'hb_effective_remediation')::text AS hb_effective_remediation,
    (fslm.performance ->> 'hb_forced_work_strike')::text AS hb_forced_work_strike,
    (fslm.performance ->> 'hb_harassment_age')::boolean AS hb_harassment_age,
    (fslm.performance ->> 'hb_harassment_disability')::boolean AS hb_harassment_disability,
    (fslm.performance ->> 'hb_harassment_hiv')::boolean AS hb_harassment_hiv,
    (fslm.performance ->> 'hb_harassment_maternitystatus')::boolean AS hb_harassment_maternitystatus,
    (fslm.performance ->> 'hb_harassment_nationality')::boolean AS hb_harassment_nationality,
    (fslm.performance ->> 'hb_harassment_other')::boolean AS hb_harassment_other,
    (fslm.performance ->> 'hb_harassment_politicalopinion')::boolean AS hb_harassment_politicalopinion,
    (fslm.performance ->> 'hb_harassment_race')::boolean AS hb_harassment_race,
    (fslm.performance ->> 'hb_harassment_religion')::boolean AS hb_harassment_religion,
    (fslm.performance ->> 'hb_harassment_sexualorientation')::boolean AS hb_harassment_sexualorientation,
    (fslm.performance ->> 'hb_immigration_threats')::text AS hb_immigration_threats,
    (fslm.performance ->> 'hb_violence_intimidation')::text AS hb_violence_intimidation,
    (fslm.performance ->> 'hb_written_recrods_threats_forcedwork')::text AS hb_written_recrods_threats_forcedwork,
    (fslm.performance ->> 'hb_writtenrecords_discp_forcedwork')::text AS hb_writtenrecords_discp_forcedwork,
    (fslm.performance ->> 'hb_writtenrecords_harassment_sexualharassment')::text AS hb_writtenrecords_harassment_sexualharassment,
    (fslm.performance ->> 'hs_accident_rootcause')::text AS hs_accident_rootcause,
    (fslm.performance ->> 'hs_air_quality')::text AS hs_air_quality,
    (fslm.performance ->> 'hs_airborne_particulates_legal_exposure')::text AS hs_airborne_particulates_legal_exposure,
    (fslm.performance ->> 'hs_alarm_system_all_emergencies')::text AS hs_alarm_system_all_emergencies,
    (fslm.performance ->> 'hs_alarm_system_no_backup')::boolean AS hs_alarm_system_no_backup,
    (fslm.performance ->> 'hs_alarm_system_no_maintenance')::boolean AS hs_alarm_system_no_maintenance,
    (fslm.performance ->> 'hs_alarm_system_not_accessible')::boolean AS hs_alarm_system_not_accessible,
    (fslm.performance ->> 'hs_alarm_system_not_distinct')::boolean AS hs_alarm_system_not_distinct,
    (fslm.performance ->> 'hs_alarm_system_not_heard')::boolean AS hs_alarm_system_not_heard,
    (fslm.performance ->> 'hs_alarm_system_notfunctioning')::boolean AS hs_alarm_system_notfunctioning,
    (fslm.performance ->> 'hs_are_pregnant_and_nursing')::text AS hs_are_pregnant_and_nursing,
    (fslm.performance ->> 'hs_bangladesh_acid_storage_legal')::text AS hs_bangladesh_acid_storage_legal,
    (fslm.performance ->> 'hs_bangladesh_overcrowding_legal_compliance')::text AS hs_bangladesh_overcrowding_legal_compliance,
    (fslm.performance ->> 'hs_building_construction_structural_legal')::text AS hs_building_construction_structural_legal,
    (fslm.performance ->> 'hs_cambodia_chemical_mixing')::text AS hs_cambodia_chemical_mixing,
    (fslm.performance ->> 'hs_cambodia_spills_legal')::text AS hs_cambodia_spills_legal,
    (fslm.performance ->> 'hs_cases_physical_integrity')::text AS hs_cases_physical_integrity,
    (fslm.performance ->> 'hs_chemical_harardous_legal')::text AS hs_chemical_harardous_legal,
    (fslm.performance ->> 'hs_chemical_practices_legal')::text AS hs_chemical_practices_legal,
    (fslm.performance ->> 'hs_chemical_shower_equipment')::text AS hs_chemical_shower_equipment,
    (fslm.performance ->> 'hs_chemicals_disposed_in_waste')::boolean AS hs_chemicals_disposed_in_waste,
    (fslm.performance ->> 'hs_chemicals_inappropriate_containers')::boolean AS hs_chemicals_inappropriate_containers,
    (fslm.performance ->> 'hs_chemicals_legal')::text AS hs_chemicals_legal,
    (fslm.performance ->> 'hs_chemicals_no_spill_kit')::boolean AS hs_chemicals_no_spill_kit,
    (fslm.performance ->> 'hs_chemicals_no_written_procedures')::boolean AS hs_chemicals_no_written_procedures,
    (fslm.performance ->> 'hs_chemicals_other')::text AS hs_chemicals_other,
    (fslm.performance ->> 'hs_children_production_area')::text AS hs_children_production_area,
    (fslm.performance ->> 'hs_comply_health_legal_requirements_hiv')::text AS hs_comply_health_legal_requirements_hiv,
    (fslm.performance ->> 'hs_confined_authorized_entry_only')::boolean AS hs_confined_authorized_entry_only,
    (fslm.performance ->> 'hs_confined_space_accidental_entry')::boolean AS hs_confined_space_accidental_entry,
    (fslm.performance ->> 'hs_confined_space_air_safety')::text AS hs_confined_space_air_safety,
    (fslm.performance ->> 'hs_confined_space_appropriate_measures')::text AS hs_confined_space_appropriate_measures,
    (fslm.performance ->> 'hs_confined_space_no_rescue_equip')::boolean AS hs_confined_space_no_rescue_equip,
    (fslm.performance ->> 'hs_confined_space_no_signs')::boolean AS hs_confined_space_no_signs,
    (fslm.performance ->> 'hs_confined_space_not_trained')::text AS hs_confined_space_not_trained,
    (fslm.performance ->> 'hs_construction_permits_dorms')::text AS hs_construction_permits_dorms,
    (fslm.performance ->> 'hs_contract_dispose_hazardous_waste')::text AS hs_contract_dispose_hazardous_waste,
    (fslm.performance ->> 'hs_cooperation_mechanisms_workers_management')::text AS hs_cooperation_mechanisms_workers_management,
    (fslm.performance ->> 'hs_does_the_facility_record')::text AS hs_does_the_facility_record,
    (fslm.performance ->> 'hs_dorm_airtight_legal')::text AS hs_dorm_airtight_legal,
    (fslm.performance ->> 'hs_dorm_cooking_legal')::text AS hs_dorm_cooking_legal,
    (fslm.performance ->> 'hs_dorm_emergencyprep_legal')::text AS hs_dorm_emergencyprep_legal,
    (fslm.performance ->> 'hs_dorm_fire_legal')::text AS hs_dorm_fire_legal,
    (fslm.performance ->> 'hs_dorm_lighting_legal')::text AS hs_dorm_lighting_legal,
    (fslm.performance ->> 'hs_dorm_noise_legal')::text AS hs_dorm_noise_legal,
    (fslm.performance ->> 'hs_dorm_permits_legal')::text AS hs_dorm_permits_legal,
    (fslm.performance ->> 'hs_dorm_pests_legal')::text AS hs_dorm_pests_legal,
    (fslm.performance ->> 'hs_dorm_ventilation_legal')::text AS hs_dorm_ventilation_legal,
    (fslm.performance ->> 'hs_dorm_wastewater_legal')::text AS hs_dorm_wastewater_legal,
    (fslm.performance ->> 'hs_dorm_water_legal')::text AS hs_dorm_water_legal,
    (fslm.performance ->> 'hs_dormitories_space_dimensions_legal')::text AS hs_dormitories_space_dimensions_legal,
    (fslm.performance ->> 'hs_dorms_legal')::text AS hs_dorms_legal,
    (fslm.performance ->> 'hs_electrical_equipment_inspection_legal')::text AS hs_electrical_equipment_inspection_legal,
    (fslm.performance ->> 'hs_electrical_maintenance')::text AS hs_electrical_maintenance,
    (fslm.performance ->> 'hs_elevators_elevatordoors_inoperable')::boolean AS hs_elevators_elevatordoors_inoperable,
    (fslm.performance ->> 'hs_elevators_inspection')::boolean AS hs_elevators_inspection,
    (fslm.performance ->> 'hs_elevators_legal')::text AS hs_elevators_legal,
    (fslm.performance ->> 'hs_elevators_loadcapacity')::boolean AS hs_elevators_loadcapacity,
    (fslm.performance ->> 'hs_elevators_safety_devices')::boolean AS hs_elevators_safety_devices,
    (fslm.performance ->> 'hs_elevators_warning_signs')::boolean AS hs_elevators_warning_signs,
    (fslm.performance ->> 'hs_emergency_alarm_legal')::text AS hs_emergency_alarm_legal,
    (fslm.performance ->> 'hs_emergency_drills')::text AS hs_emergency_drills,
    (fslm.performance ->> 'hs_emergency_exit_doors')::boolean AS hs_emergency_exit_doors,
    (fslm.performance ->> 'hs_emergency_exits_marked')::text AS hs_emergency_exits_marked,
    (fslm.performance ->> 'hs_emergency_exits_safe')::text AS hs_emergency_exits_safe,
    (fslm.performance ->> 'hs_emergency_response_vehicles')::text AS hs_emergency_response_vehicles,
    (fslm.performance ->> 'hs_emergencyexits_legal')::text AS hs_emergencyexits_legal,
    (fslm.performance ->> 'hs_ergonomics')::text AS hs_ergonomics,
    (fslm.performance ->> 'hs_evacuation_legal')::text AS hs_evacuation_legal,
    (fslm.performance ->> 'hs_evacuationplans_legal')::text AS hs_evacuationplans_legal,
    (fslm.performance ->> 'hs_facility_provides_drinking_water')::text AS hs_facility_provides_drinking_water,
    (fslm.performance ->> 'hs_facilitydoors_legal')::text AS hs_facilitydoors_legal,
    (fslm.performance ->> 'hs_fallprotection_designated_location')::boolean AS hs_fallprotection_designated_location,
    (fslm.performance ->> 'hs_fallprotection_maintenance_logs')::boolean AS hs_fallprotection_maintenance_logs,
    (fslm.performance ->> 'hs_fallprotection_not_trained')::boolean AS hs_fallprotection_not_trained,
    (fslm.performance ->> 'hs_fallprotection_not_worn_at_all_times')::boolean AS hs_fallprotection_not_worn_at_all_times,
    (fslm.performance ->> 'hs_fallprotection_notgoodcondition')::boolean AS hs_fallprotection_notgoodcondition,
    (fslm.performance ->> 'hs_fallprotection_notusing')::boolean AS hs_fallprotection_notusing,
    (fslm.performance ->> 'hs_fallprotection_nowalls')::boolean AS hs_fallprotection_nowalls,
    (fslm.performance ->> 'hs_fallprotection_training_logs')::boolean AS hs_fallprotection_training_logs,
    (fslm.performance ->> 'hs_fire_alarms_legal')::text AS hs_fire_alarms_legal,
    (fslm.performance ->> 'hs_fire_detection_legal')::text AS hs_fire_detection_legal,
    (fslm.performance ->> 'hs_fire_training')::text AS hs_fire_training,
    (fslm.performance ->> 'hs_firefighting_equipment_legal')::text AS hs_firefighting_equipment_legal,
    (fslm.performance ->> 'hs_firefighting_equipment_not_accessible')::boolean AS hs_firefighting_equipment_not_accessible,
    (fslm.performance ->> 'hs_firefighting_non')::boolean AS hs_firefighting_non,
    (fslm.performance ->> 'hs_firefighting_not_marked')::boolean AS hs_firefighting_not_marked,
    (fslm.performance ->> 'hs_firefighting_training_legal')::text AS hs_firefighting_training_legal,
    (fslm.performance ->> 'hs_first_aid_kits_not_accessible')::text AS hs_first_aid_kits_not_accessible,
    (fslm.performance ->> 'hs_first_aid_kits_not_maintained')::text AS hs_first_aid_kits_not_maintained,
    (fslm.performance ->> 'hs_first_aid_kits_not_sufficient')::text AS hs_first_aid_kits_not_sufficient,
    (fslm.performance ->> 'hs_flammable_materials_not_stored_safely')::text AS hs_flammable_materials_not_stored_safely,
    (fslm.performance ->> 'hs_foodservice_permits_legal')::text AS hs_foodservice_permits_legal,
    (fslm.performance ->> 'hs_free_drinking_water')::text AS hs_free_drinking_water,
    (fslm.performance ->> 'hs_fuel_storage_legal')::text AS hs_fuel_storage_legal,
    (fslm.performance ->> 'hs_ghs_available')::text AS hs_ghs_available,
    (fslm.performance ->> 'hs_hazardous_substances_exposure')::text AS hs_hazardous_substances_exposure,
    (fslm.performance ->> 'hs_hazardous_substances_exposure_label')::text AS hs_hazardous_substances_exposure_label,
    (fslm.performance ->> 'hs_hazardous_substances_legal')::text AS hs_hazardous_substances_legal,
    (fslm.performance ->> 'hs_hazardous_work_monitoring_legal')::text AS hs_hazardous_work_monitoring_legal,
    (fslm.performance ->> 'hs_health_safety_risk_assessment_conducted')::text AS hs_health_safety_risk_assessment_conducted,
    (fslm.performance ->> 'hs_hot_work_legal')::text AS hs_hot_work_legal,
    (fslm.performance ->> 'hs_hs_assessment')::text AS hs_hs_assessment,
    (fslm.performance ->> 'hs_ignition_sources_not_safeguarded')::text AS hs_ignition_sources_not_safeguarded,
    (fslm.performance ->> 'hs_initial_and_refresher_trainings_firefighting')::boolean AS hs_initial_and_refresher_trainings_firefighting,
    (fslm.performance ->> 'hs_inventory_hazardous_substances')::text AS hs_inventory_hazardous_substances,
    (fslm.performance ->> 'hs_laser_radiation_legal')::text AS hs_laser_radiation_legal,
    (fslm.performance ->> 'hs_legal_equipment_eyewash')::text AS hs_legal_equipment_eyewash,
    (fslm.performance ->> 'hs_legally_required_facilities_provided')::text AS hs_legally_required_facilities_provided,
    (fslm.performance ->> 'hs_lighting_legal')::text AS hs_lighting_legal,
    (fslm.performance ->> 'hs_lightning_protector_legal')::text AS hs_lightning_protector_legal,
    (fslm.performance ->> 'hs_machinery_maintenance_of_worker_machinery')::boolean AS hs_machinery_maintenance_of_worker_machinery,
    (fslm.performance ->> 'hs_machinery_no_instructions_language')::boolean AS hs_machinery_no_instructions_language,
    (fslm.performance ->> 'hs_medical_checks_legal')::text AS hs_medical_checks_legal,
    (fslm.performance ->> 'hs_medical_emergency_arrangements')::text AS hs_medical_emergency_arrangements,
    (fslm.performance ->> 'hs_negative_consequences_removing_dangerous_situation')::text AS hs_negative_consequences_removing_dangerous_situation,
    (fslm.performance ->> 'hs_no_automatic_and_centralized')::boolean AS hs_no_automatic_and_centralized,
    (fslm.performance ->> 'hs_no_back_up_battery_ee_lighting')::boolean AS hs_no_back_up_battery_ee_lighting,
    (fslm.performance ->> 'hs_no_equipment_firefighting')::boolean AS hs_no_equipment_firefighting,
    (fslm.performance ->> 'hs_no_fire_resistant_walls')::boolean AS hs_no_fire_resistant_walls,
    (fslm.performance ->> 'hs_no_first_aid_records')::text AS hs_no_first_aid_records,
    (fslm.performance ->> 'hs_no_first_aid_training')::text AS hs_no_first_aid_training,
    (fslm.performance ->> 'hs_no_functioning_lockout_or_tagout')::text AS hs_no_functioning_lockout_or_tagout,
    (fslm.performance ->> 'hs_no_illumination_ee')::boolean AS hs_no_illumination_ee,
    (fslm.performance ->> 'hs_no_marking_nor_exit')::boolean AS hs_no_marking_nor_exit,
    (fslm.performance ->> 'hs_noise_exposure_legal_compliance')::text AS hs_noise_exposure_legal_compliance,
    (fslm.performance ->> 'hs_noise_level_legal')::text AS hs_noise_level_legal,
    (fslm.performance ->> 'hs_noise_testing')::text AS hs_noise_testing,
    (fslm.performance ->> 'hs_non_prod_hs_noncompliance')::text AS hs_non_prod_hs_noncompliance,
    (fslm.performance ->> 'hs_off_site_canteens_legal')::text AS hs_off_site_canteens_legal,
    (fslm.performance ->> 'hs_onsite_canteens_legal')::text AS hs_onsite_canteens_legal,
    (fslm.performance ->> 'hs_onsite_childcare_legal')::text AS hs_onsite_childcare_legal,
    (fslm.performance ->> 'hs_osh_committee_formed_and_functioning')::text AS hs_osh_committee_formed_and_functioning,
    (fslm.performance ->> 'hs_osh_committee_wo_legal')::text AS hs_osh_committee_wo_legal,
    (fslm.performance ->> 'hs_osh_cost_to_workers')::text AS hs_osh_cost_to_workers,
    (fslm.performance ->> 'hs_other_health_safety_legal_noncompliance')::text AS hs_other_health_safety_legal_noncompliance,
    (fslm.performance ->> 'hs_outlets_wet_area')::text AS hs_outlets_wet_area,
    (fslm.performance ->> 'hs_pcb')::text AS hs_pcb,
    (fslm.performance ->> 'hs_ppe_for_dmf')::text AS hs_ppe_for_dmf,
    (fslm.performance ->> 'hs_ppe_for_dmf_condition')::text AS hs_ppe_for_dmf_condition,
    (fslm.performance ->> 'hs_ppe_for_perc')::text AS hs_ppe_for_perc,
    (fslm.performance ->> 'hs_ppe_for_perc_condition')::text AS hs_ppe_for_perc_condition,
    (fslm.performance ->> 'hs_ppe_for_pp')::text AS hs_ppe_for_pp,
    (fslm.performance ->> 'hs_ppe_for_pp_condition')::text AS hs_ppe_for_pp_condition,
    (fslm.performance ->> 'hs_ppe_training_legal')::text AS hs_ppe_training_legal,
    (fslm.performance ->> 'hs_prevent_floor_opening')::text AS hs_prevent_floor_opening,
    (fslm.performance ->> 'hs_prevent_slips')::text AS hs_prevent_slips,
    (fslm.performance ->> 'hs_prevent_standing_water')::text AS hs_prevent_standing_water,
    (fslm.performance ->> 'hs_provided_ppe_legal')::text AS hs_provided_ppe_legal,
    (fslm.performance ->> 'hs_qualified_osh_staff_legal_requirement')::text AS hs_qualified_osh_staff_legal_requirement,
    (fslm.performance ->> 'hs_required_guards_legal')::text AS hs_required_guards_legal,
    (fslm.performance ->> 'hs_required_training_free')::text AS hs_required_training_free,
    (fslm.performance ->> 'hs_safety_warnings_legally_posted')::text AS hs_safety_warnings_legally_posted,
    (fslm.performance ->> 'hs_sanitation_practices_legal_compliance')::text AS hs_sanitation_practices_legal_compliance,
    (fslm.performance ->> 'hs_sufficient_emergency')::text AS hs_sufficient_emergency,
    (fslm.performance ->> 'hs_sufficient_toilets_legal')::text AS hs_sufficient_toilets_legal,
    (fslm.performance ->> 'hs_sustation_legal')::text AS hs_sustation_legal,
    (fslm.performance ->> 'hs_temperature_ventilation_legal_compliance')::text AS hs_temperature_ventilation_legal_compliance,
    (fslm.performance ->> 'hs_tempsystems_legal')::text AS hs_tempsystems_legal,
    (fslm.performance ->> 'hs_test_fire_alarms')::text AS hs_test_fire_alarms,
    (fslm.performance ->> 'hs_toilets_legal_requirements_met')::text AS hs_toilets_legal_requirements_met,
    (fslm.performance ->> 'hs_training_records_chemical_12months')::boolean AS hs_training_records_chemical_12months,
    (fslm.performance ->> 'hs_vietnam_annual_osh_plan')::text AS hs_vietnam_annual_osh_plan,
    (fslm.performance ->> 'hs_vietnam_environmental_conditions_monitoring')::text AS hs_vietnam_environmental_conditions_monitoring,
    (fslm.performance ->> 'hs_vietnam_maintenance_machinery_legal')::text AS hs_vietnam_maintenance_machinery_legal,
    (fslm.performance ->> 'hs_vietnam_occupational_health_legal')::text AS hs_vietnam_occupational_health_legal,
    (fslm.performance ->> 'hs_waste_discharge_permits')::text AS hs_waste_discharge_permits,
    (fslm.performance ->> 'hs_waste_disposal_legal_compliance')::text AS hs_waste_disposal_legal_compliance,
    (fslm.performance ->> 'hs_worker_access_drinking_water_anytime')::text AS hs_worker_access_drinking_water_anytime,
    (fslm.performance ->> 'hs_worker_access_toilets_anytime')::text AS hs_worker_access_toilets_anytime,
    (fslm.performance ->> 'hs_written_osh_policy_legal_compliance')::text AS hs_written_osh_policy_legal_compliance,
    (fslm.performance ->> 'rh_age_jd')::text AS rh_age_jd,
    (fslm.performance ->> 'rh_age_referenced')::text AS rh_age_referenced,
    (fslm.performance ->> 'rh_bangladesh_do_all_workers')::text AS rh_bangladesh_do_all_workers,
    (fslm.performance ->> 'rh_cambodia_entitlements_legal')::text AS rh_cambodia_entitlements_legal,
    (fslm.performance ->> 'rh_child_labor_hours_exceeded')::boolean AS rh_child_labor_hours_exceeded,
    (fslm.performance ->> 'rh_child_labor_legal_noncompliance')::text AS rh_child_labor_legal_noncompliance,
    (fslm.performance ->> 'rh_child_worker_registry')::text AS rh_child_worker_registry,
    (fslm.performance ->> 'rh_contract_practices_legal')::text AS rh_contract_practices_legal,
    (fslm.performance ->> 'rh_contract_practices_nonprod_legal')::text AS rh_contract_practices_nonprod_legal,
    (fslm.performance ->> 'rh_contracts_do_not_clearly')::boolean AS rh_contracts_do_not_clearly,
    (fslm.performance ->> 'rh_copies_of_contracts_are')::text AS rh_copies_of_contracts_are,
    (fslm.performance ->> 'rh_disability_referenced')::text AS rh_disability_referenced,
    (fslm.performance ->> 'rh_discrimination_noncompliance')::text AS rh_discrimination_noncompliance,
    (fslm.performance ->> 'rh_family_responsibilities')::text AS rh_family_responsibilities,
    (fslm.performance ->> 'rh_family_responsibilities_hiring')::text AS rh_family_responsibilities_hiring,
    (fslm.performance ->> 'rh_family_responsibilities_jd')::text AS rh_family_responsibilities_jd,
    (fslm.performance ->> 'rh_forced_labor_underage')::text AS rh_forced_labor_underage,
    (fslm.performance ->> 'rh_hiv_status_hiring')::text AS rh_hiv_status_hiring,
    (fslm.performance ->> 'rh_hiv_status_referenced')::text AS rh_hiv_status_referenced,
    (fslm.performance ->> 'rh_hiv_testing_jd')::text AS rh_hiv_testing_jd,
    (fslm.performance ->> 'rh_homeworkers_legal')::text AS rh_homeworkers_legal,
    (fslm.performance ->> 'rh_illness_testing_hiring_legal')::text AS rh_illness_testing_hiring_legal,
    (fslm.performance ->> 'rh_indonesia_outsourced_legal')::text AS rh_indonesia_outsourced_legal,
    (fslm.performance ->> 'rh_job_application_discrimination')::text AS rh_job_application_discrimination,
    (fslm.performance ->> 'rh_job_description_discrimination')::text AS rh_job_description_discrimination,
    (fslm.performance ->> 'rh_marital_status_hiring')::text AS rh_marital_status_hiring,
    (fslm.performance ->> 'rh_marital_status_referenced')::text AS rh_marital_status_referenced,
    (fslm.performance ->> 'rh_migrant_contracts_legal')::text AS rh_migrant_contracts_legal,
    (fslm.performance ->> 'rh_monetary_deposits_legal')::text AS rh_monetary_deposits_legal,
    (fslm.performance ->> 'rh_national_extraction_hiring')::boolean AS rh_national_extraction_hiring,
    (fslm.performance ->> 'rh_national_extraction_referenced')::boolean AS rh_national_extraction_referenced,
    (fslm.performance ->> 'rh_nationality_jd')::text AS rh_nationality_jd,
    (fslm.performance ->> 'rh_nationality_referenced')::text AS rh_nationality_referenced,
    (fslm.performance ->> 'rh_other_identified_jd')::text AS rh_other_identified_jd,
    (fslm.performance ->> 'rh_political_opinion_hiring')::boolean AS rh_political_opinion_hiring,
    (fslm.performance ->> 'rh_political_opinion_referenced')::boolean AS rh_political_opinion_referenced,
    (fslm.performance ->> 'rh_pregnancy_hiring')::boolean AS rh_pregnancy_hiring,
    (fslm.performance ->> 'rh_pregnancy_referenced')::boolean AS rh_pregnancy_referenced,
    (fslm.performance ->> 'rh_pregnancy_testing')::boolean AS rh_pregnancy_testing,
    (fslm.performance ->> 'rh_prison_laborers_have_not')::boolean AS rh_prison_laborers_have_not,
    (fslm.performance ->> 'rh_race_ethnic_group_skin')::boolean AS rh_race_ethnic_group_skin,
    (fslm.performance ->> 'rh_race_ethnic_group_skin_jd')::boolean AS rh_race_ethnic_group_skin_jd,
    (fslm.performance ->> 'rh_religion_hiring')::boolean AS rh_religion_hiring,
    (fslm.performance ->> 'rh_religion_referenced_hiring')::boolean AS rh_religion_referenced_hiring,
    (fslm.performance ->> 'rh_sex_gender_hiring')::boolean AS rh_sex_gender_hiring,
    (fslm.performance ->> 'rh_sex_gender_jd')::boolean AS rh_sex_gender_jd,
    (fslm.performance ->> 'rh_sexual_orientation_hiring')::text AS rh_sexual_orientation_hiring,
    (fslm.performance ->> 'rh_sexual_orientation_referenced')::text AS rh_sexual_orientation_referenced,
    (fslm.performance ->> 'rh_signed_copies_of_contracts')::boolean AS rh_signed_copies_of_contracts,
    (fslm.performance ->> 'rh_social_origin_hiring')::boolean AS rh_social_origin_hiring,
    (fslm.performance ->> 'rh_social_origin_referenced')::boolean AS rh_social_origin_referenced,
    (fslm.performance ->> 'rh_the_facility_does_not')::boolean AS rh_the_facility_does_not,
    (fslm.performance ->> 'rh_there_is_no_supervision')::boolean AS rh_there_is_no_supervision,
    (fslm.performance ->> 'rh_vietnam_disability_legal')::text AS rh_vietnam_disability_legal,
    (fslm.performance ->> 'rh_worker_privacy')::text AS rh_worker_privacy,
    (fslm.performance ->> 'rh_workplace_legal')::text AS rh_workplace_legal,
    (fslm.performance ->> 'ter_debt_bondage_risk')::text AS ter_debt_bondage_risk,
    (fslm.performance ->> 'ter_family_responsibilities')::boolean AS ter_family_responsibilities,
    (fslm.performance ->> 'ter_invalid_termination_reasons')::text AS ter_invalid_termination_reasons,
    (fslm.performance ->> 'ter_legal_compliance')::text AS ter_legal_compliance,
    (fslm.performance ->> 'ter_other_discrimination')::text AS ter_other_discrimination,
    (fslm.performance ->> 'ter_race_ethnic_group')::text AS ter_race_ethnic_group,
    (fslm.performance ->> 'ter_reinstatement_orders_not_followed')::boolean AS ter_reinstatement_orders_not_followed,
    (fslm.performance ->> 'ter_severance_not_paid')::text AS ter_severance_not_paid,
    (fslm.performance ->> 'ter_suspension_legal_compliance')::text AS ter_suspension_legal_compliance,
    (fslm.performance ->> 'ter_termination_benefits_not_paid')::text AS ter_termination_benefits_not_paid,
    (fslm.performance ->> 'ter_termination_noncompliance_general')::text AS ter_termination_noncompliance_general,
    (fslm.performance ->> 'ter_termination_nonprod_noncompliance')::text AS ter_termination_nonprod_noncompliance,
    (fslm.performance ->> 'ter_termination_payment_delay')::text AS ter_termination_payment_delay,
    (fslm.performance ->> 'ter_unused_leave_not_paid')::text AS ter_unused_leave_not_paid,
    (fslm.performance ->> 'wb_accurate_detailed_payslips')::text AS wb_accurate_detailed_payslips,
    (fslm.performance ->> 'wb_agencycontract_workers')::text AS wb_agencycontract_workers,
    (fslm.performance ->> 'wb_annual_leave_failing_to_pay')::boolean AS wb_annual_leave_failing_to_pay,
    (fslm.performance ->> 'wb_authorized_3rd_party_agents')::text AS wb_authorized_3rd_party_agents,
    (fslm.performance ->> 'wb_bangladesh_has_facility_established')::text AS wb_bangladesh_has_facility_established,
    (fslm.performance ->> 'wb_bangladesh_workers_participation_welfare')::text AS wb_bangladesh_workers_participation_welfare,
    (fslm.performance ->> 'wb_cambodia_attendance_bonus_casual')::boolean AS wb_cambodia_attendance_bonus_casual,
    (fslm.performance ->> 'wb_cambodia_attendance_bonus_during')::boolean AS wb_cambodia_attendance_bonus_during,
    (fslm.performance ->> 'wb_cambodia_attendance_bonus_new')::boolean AS wb_cambodia_attendance_bonus_new,
    (fslm.performance ->> 'wb_cambodia_piece_rate_set')::text AS wb_cambodia_piece_rate_set,
    (fslm.performance ->> 'wb_cambodia_seniority_indemnity_undetermined')::boolean AS wb_cambodia_seniority_indemnity_undetermined,
    (fslm.performance ->> 'wb_cambodia_transport_home_place')::boolean AS wb_cambodia_transport_home_place,
    (fslm.performance ->> 'wb_cambodia_wage_supplements_including')::boolean AS wb_cambodia_wage_supplements_including,
    (fslm.performance ->> 'wb_casual_workers')::text AS wb_casual_workers,
    (fslm.performance ->> 'wb_compensation_workers_death')::boolean AS wb_compensation_workers_death,
    (fslm.performance ->> 'wb_compensation_workrelated_accidents_diseases')::boolean AS wb_compensation_workrelated_accidents_diseases,
    (fslm.performance ->> 'wb_compensatorytimeoff_legal')::text AS wb_compensatorytimeoff_legal,
    (fslm.performance ->> 'wb_compulsory_group_insurance_workers')::boolean AS wb_compulsory_group_insurance_workers,
    (fslm.performance ->> 'wb_confirm_accuracy_writing')::text AS wb_confirm_accuracy_writing,
    (fslm.performance ->> 'wb_contract_workers_who_part')::text AS wb_contract_workers_who_part,
    (fslm.performance ->> 'wb_deductions_injury')::text AS wb_deductions_injury,
    (fslm.performance ->> 'wb_deductions_maternity')::text AS wb_deductions_maternity,
    (fslm.performance ->> 'wb_deductions_medical')::text AS wb_deductions_medical,
    (fslm.performance ->> 'wb_deductions_unemployment')::text AS wb_deductions_unemployment,
    (fslm.performance ->> 'wb_deductions_voluntarily_accepted_workers')::boolean AS wb_deductions_voluntarily_accepted_workers,
    (fslm.performance ->> 'wb_deductions_wages_explained_workers')::boolean AS wb_deductions_wages_explained_workers,
    (fslm.performance ->> 'wb_dispute_correct_wages')::text AS wb_dispute_correct_wages,
    (fslm.performance ->> 'wb_ethiopia_correct_time_off')::text AS wb_ethiopia_correct_time_off,
    (fslm.performance ->> 'wb_ethiopia_provide_legally_required')::text AS wb_ethiopia_provide_legally_required,
    (fslm.performance ->> 'wb_ethiopia_provide_prenatal')::text AS wb_ethiopia_provide_prenatal,
    (fslm.performance ->> 'wb_ethiopia_provide_time_off')::text AS wb_ethiopia_provide_time_off,
    (fslm.performance ->> 'wb_facility_comply_leave_legal')::text AS wb_facility_comply_leave_legal,
    (fslm.performance ->> 'wb_facility_conduct_worker_performance')::text AS wb_facility_conduct_worker_performance,
    (fslm.performance ->> 'wb_facility_failing_comply_legal')::text AS wb_facility_failing_comply_legal,
    (fslm.performance ->> 'wb_facility_failing_correctly_provide')::text AS wb_facility_failing_correctly_provide,
    (fslm.performance ->> 'wb_facility_failing_leave_legal_other')::text AS wb_facility_failing_leave_legal_other,
    (fslm.performance ->> 'wb_facility_failing_pay_worker_basicwage')::text AS wb_facility_failing_pay_worker_basicwage,
    (fslm.performance ->> 'wb_facility_failing_pay_worker_cba')::text AS wb_facility_failing_pay_worker_cba,
    (fslm.performance ->> 'wb_facility_failing_pay_worker_legalmin')::text AS wb_facility_failing_pay_worker_legalmin,
    (fslm.performance ->> 'wb_facility_failing_pay_workers_experience')::text AS wb_facility_failing_pay_workers_experience,
    (fslm.performance ->> 'wb_facility_failing_pay_workers_overtime')::text AS wb_facility_failing_pay_workers_overtime,
    (fslm.performance ->> 'wb_facility_failing_pay_workers_overtime_legal')::text AS wb_facility_failing_pay_workers_overtime_legal,
    (fslm.performance ->> 'wb_facility_failing_pay_workers_regular')::text AS wb_facility_failing_pay_workers_regular,
    (fslm.performance ->> 'wb_facility_has_overdue_social')::text AS wb_facility_has_overdue_social,
    (fslm.performance ->> 'wb_facility_paid_annual_bonus')::text AS wb_facility_paid_annual_bonus,
    (fslm.performance ->> 'wb_facility_paid_attendance_bonus')::text AS wb_facility_paid_attendance_bonus,
    (fslm.performance ->> 'wb_facility_paid_housing_allowance')::text AS wb_facility_paid_housing_allowance,
    (fslm.performance ->> 'wb_facility_paid_meal_allowance')::text AS wb_facility_paid_meal_allowance,
    (fslm.performance ->> 'wb_facility_paid_productivity_bonus')::text AS wb_facility_paid_productivity_bonus,
    (fslm.performance ->> 'wb_facility_paid_seniority_andor')::text AS wb_facility_paid_seniority_andor,
    (fslm.performance ->> 'wb_facility_paid_transportation_allowance')::text AS wb_facility_paid_transportation_allowance,
    (fslm.performance ->> 'wb_facility_pay_workers_correctly')::text AS wb_facility_pay_workers_correctly,
    (fslm.performance ->> 'wb_facility_provide_legally_required')::text AS wb_facility_provide_legally_required,
    (fslm.performance ->> 'wb_facility_provide_other_insurance')::text AS wb_facility_provide_other_insurance,
    (fslm.performance ->> 'wb_facility_register_workers_social')::text AS wb_facility_register_workers_social,
    (fslm.performance ->> 'wb_facility_take_deductions_wages')::text AS wb_facility_take_deductions_wages,
    (fslm.performance ->> 'wb_failing_topay_leave')::text AS wb_failing_topay_leave,
    (fslm.performance ->> 'wb_failing_topay_overtime_night')::boolean AS wb_failing_topay_overtime_night,
    (fslm.performance ->> 'wb_failing_topay_overtime_ordinary')::boolean AS wb_failing_topay_overtime_ordinary,
    (fslm.performance ->> 'wb_failing_topay_overtime_public_holidays')::boolean AS wb_failing_topay_overtime_public_holidays,
    (fslm.performance ->> 'wb_failing_topay_overtime_weekly_restdays')::boolean AS wb_failing_topay_overtime_weekly_restdays,
    (fslm.performance ->> 'wb_indonesia_facility_comply_legal')::text AS wb_indonesia_facility_comply_legal,
    (fslm.performance ->> 'wb_indonesia_facility_comply_requirements')::text AS wb_indonesia_facility_comply_requirements,
    (fslm.performance ->> 'wb_indonesia_facility_establish_wage')::text AS wb_indonesia_facility_establish_wage,
    (fslm.performance ->> 'wb_indonesia_nationalhealthcare')::text AS wb_indonesia_nationalhealthcare,
    (fslm.performance ->> 'wb_inkind_benefits_legal')::text AS wb_inkind_benefits_legal,
    (fslm.performance ->> 'wb_loans_legal')::text AS wb_loans_legal,
    (fslm.performance ->> 'wb_maternity_collected_forwarded')::text AS wb_maternity_collected_forwarded,
    (fslm.performance ->> 'wb_maternity_leave_failing_to_pay')::boolean AS wb_maternity_leave_failing_to_pay,
    (fslm.performance ->> 'wb_medical_collected_forwarded')::text AS wb_medical_collected_forwarded,
    (fslm.performance ->> 'wb_one_payroll_record')::text AS wb_one_payroll_record,
    (fslm.performance ->> 'wb_other')::boolean AS wb_other,
    (fslm.performance ->> 'wb_other_collected_forwarded')::text AS wb_other_collected_forwarded,
    (fslm.performance ->> 'wb_other_monetary_bonuses_andor')::text AS wb_other_monetary_bonuses_andor,
    (fslm.performance ->> 'wb_other_types_required_leave_failing_to_pay')::boolean AS wb_other_types_required_leave_failing_to_pay,
    (fslm.performance ->> 'wb_overtime_allowances_providedpaid_line')::text AS wb_overtime_allowances_providedpaid_line,
    (fslm.performance ->> 'wb_overtime_premium')::text AS wb_overtime_premium,
    (fslm.performance ->> 'wb_pakistan_employer_maintain_fair')::text AS wb_pakistan_employer_maintain_fair,
    (fslm.performance ->> 'wb_pakistan_facility_pay_workers')::text AS wb_pakistan_facility_pay_workers,
    (fslm.performance ->> 'wb_pakistan_iddat_leave')::text AS wb_pakistan_iddat_leave,
    (fslm.performance ->> 'wb_pakistan_workers_receive_correct')::text AS wb_pakistan_workers_receive_correct,
    (fslm.performance ->> 'wb_pakistan_workers_survivors_benefit')::text AS wb_pakistan_workers_survivors_benefit,
    (fslm.performance ->> 'wb_pakistan_workers_survivors_injury')::text AS wb_pakistan_workers_survivors_injury,
    (fslm.performance ->> 'wb_pakistan_workers_survivors_medical')::text AS wb_pakistan_workers_survivors_medical,
    (fslm.performance ->> 'wb_parttime_workers_failing_timeoff')::text AS wb_parttime_workers_failing_timeoff,
    (fslm.performance ->> 'wb_paternity_leave_failing_to_pay')::boolean AS wb_paternity_leave_failing_to_pay,
    (fslm.performance ->> 'wb_payroll_records_consistent_attendance')::boolean AS wb_payroll_records_consistent_attendance,
    (fslm.performance ->> 'wb_payroll_records_each_worker')::boolean AS wb_payroll_records_each_worker,
    (fslm.performance ->> 'wb_payroll_records_show_types')::text AS wb_payroll_records_show_types,
    (fslm.performance ->> 'wb_pension_provident_fund_collected')::text AS wb_pension_provident_fund_collected,
    (fslm.performance ->> 'wb_pension_provident_fund_collected_legal')::text AS wb_pension_provident_fund_collected_legal,
    (fslm.performance ->> 'wb_permanent_workers')::text AS wb_permanent_workers,
    (fslm.performance ->> 'wb_personal_leave_failing_to_pay')::boolean AS wb_personal_leave_failing_to_pay,
    (fslm.performance ->> 'wb_piece_rate_workers_paid')::text AS wb_piece_rate_workers_paid,
    (fslm.performance ->> 'wb_premiumpay_night')::text AS wb_premiumpay_night,
    (fslm.performance ->> 'wb_premiumpay_public_holidays')::text AS wb_premiumpay_public_holidays,
    (fslm.performance ->> 'wb_premiumpay_weeklyrestdays')::text AS wb_premiumpay_weeklyrestdays,
    (fslm.performance ->> 'wb_public_holidays_failing_to_pay')::boolean AS wb_public_holidays_failing_to_pay,
    (fslm.performance ->> 'wb_sick_leave_failing_to_pay')::boolean AS wb_sick_leave_failing_to_pay,
    (fslm.performance ->> 'wb_temporary_workers')::text AS wb_temporary_workers,
    (fslm.performance ->> 'wb_unemployment_collected_forwarded')::text AS wb_unemployment_collected_forwarded,
    (fslm.performance ->> 'wb_vietnam_facility_collect_forward')::text AS wb_vietnam_facility_collect_forward,
    (fslm.performance ->> 'wb_vietnam_facility_comply_applicable')::text AS wb_vietnam_facility_comply_applicable,
    (fslm.performance ->> 'wb_vietnam_facility_contribution_social')::text AS wb_vietnam_facility_contribution_social,
    (fslm.performance ->> 'wb_vietnam_facility_incorporate_legally')::text AS wb_vietnam_facility_incorporate_legally,
    (fslm.performance ->> 'wb_vietnam_facility_submit_claims')::text AS wb_vietnam_facility_submit_claims,
    (fslm.performance ->> 'wb_vietnam_provide_period_break')::text AS wb_vietnam_provide_period_break,
    (fslm.performance ->> 'wb_vietnam_failing_to_pay_period_leave')::text AS wb_vietnam_failing_to_pay_period_leave,
    (fslm.performance ->> 'wb_wage_basis_legal_requirements')::boolean AS wb_wage_basis_legal_requirements,
    (fslm.performance ->> 'wb_wage_payments_made_regularly')::text AS wb_wage_payments_made_regularly,
    (fslm.performance ->> 'wb_were_other_wage_payments')::text AS wb_were_other_wage_payments,
    (fslm.performance ->> 'wb_were_withholdings_wages_other')::text AS wb_were_withholdings_wages_other,
    (fslm.performance ->> 'wb_workers_access_account_status')::boolean AS wb_workers_access_account_status,
    (fslm.performance ->> 'wb_workers_give_written_consent')::boolean AS wb_workers_give_written_consent,
    (fslm.performance ->> 'wb_workers_informed_about_individual')::text AS wb_workers_informed_about_individual,
    (fslm.performance ->> 'wb_workers_paid_full_wages')::text AS wb_workers_paid_full_wages,
    (fslm.performance ->> 'wb_workers_paid_workrelated_activities')::text AS wb_workers_paid_workrelated_activities,
    (fslm.performance ->> 'wb_workers_under_probation')::text AS wb_workers_under_probation,
    (fslm.performance ->> 'wb_workers_were_paid_correctly')::text AS wb_workers_were_paid_correctly,
    (fslm.performance ->> 'wb_workers_who_trainees_apprentices')::text AS wb_workers_who_trainees_apprentices,
    (fslm.performance ->> 'wb_workrelated_injury_illness_death')::text AS wb_workrelated_injury_illness_death,
    (fslm.performance ->> 'wb_written_terms_legal')::text AS wb_written_terms_legal,
    (fslm.performance ->> 'wh_breastfeeding_legal')::text AS wh_breastfeeding_legal,
    (fslm.performance ->> 'wh_exceed_legal_requirements')::text AS wh_exceed_legal_requirements,
    (fslm.performance ->> 'wh_facility_failing_comply_legal_nonprod')::text AS wh_facility_failing_comply_legal_nonprod,
    (fslm.performance ->> 'wh_facility_failing_comply_legal_other')::text AS wh_facility_failing_comply_legal_other,
    (fslm.performance ->> 'wh_facility_maintain_only_one')::text AS wh_facility_maintain_only_one,
    (fslm.performance ->> 'wh_facility_only_require_workers')::text AS wh_facility_only_require_workers,
    (fslm.performance ->> 'wh_facility_provide_breaks_during')::text AS wh_facility_provide_breaks_during,
    (fslm.performance ->> 'wh_govt_permission_legal')::text AS wh_govt_permission_legal,
    (fslm.performance ->> 'wh_no_impact_workers_workers')::boolean AS wh_no_impact_workers_workers,
    (fslm.performance ->> 'wh_other_action_impacting_workers')::boolean AS wh_other_action_impacting_workers,
    (fslm.performance ->> 'wh_overtime_voluntary_line_legal')::text AS wh_overtime_voluntary_line_legal,
    (fslm.performance ->> 'wh_overtime_working_hours_line')::text AS wh_overtime_working_hours_line,
    (fslm.performance ->> 'wh_pakistan_provide_required_time')::text AS wh_pakistan_provide_required_time,
    (fslm.performance ->> 'wh_reasons_overtime_line_legal')::text AS wh_reasons_overtime_line_legal,
    (fslm.performance ->> 'wh_vietnam_facility_comply_legal')::text AS wh_vietnam_facility_comply_legal,
    (fslm.performance ->> 'wh_weeklyrestdays_legal')::text AS wh_weeklyrestdays_legal,
    (fslm.performance ->> 'wh_work_targets_production_eg')::text AS wh_work_targets_production_eg,
    (fslm.performance ->> 'wh_records_kept_12m')::boolean AS wh_records_kept_12m,
    (fslm.performance ->> 'wh_workers_hours_reduced')::boolean AS wh_workers_hours_reduced,
    (fslm.performance ->> 'wh_workers_must_stay_home_less_minwage')::boolean AS wh_workers_must_stay_home_less_minwage,
    (fslm.performance ->> 'wh_workers_must_stay_home_minwage')::boolean AS wh_workers_must_stay_home_minwage,
    (fslm.performance ->> 'wh_workers_must_stay_home_notpaid')::boolean AS wh_workers_must_stay_home_notpaid,
    (fslm.performance ->> 'wh_workers_must_stay_home_pto')::boolean AS wh_workers_must_stay_home_pto,
    (fslm.performance ->> 'wh_yes_regular_hours_exceed')::text AS wh_yes_regular_hours_exceed,
    (fslm.performance ->> 'wi_bangladesh_facility_legally_required')::text AS wi_bangladesh_facility_legally_required,
    (fslm.performance ->> 'wi_bipartite_committees_established_functioning')::text AS wi_bipartite_committees_established_functioning,
    (fslm.performance ->> 'wi_employer_allow_workers_carry')::text AS wi_employer_allow_workers_carry,
    (fslm.performance ->> 'wi_facility_failing_comply_legal')::text AS wi_facility_failing_comply_legal,
    (fslm.performance ->> 'wi_facility_has_no_trade')::text AS wi_facility_has_no_trade,
    (fslm.performance ->> 'wi_facility_inform_workers_about')::text AS wi_facility_inform_workers_about,
    (fslm.performance ->> 'wi_facility_refuse_bargain_collectively')::text AS wi_facility_refuse_bargain_collectively,
    (fslm.performance ->> 'wi_grievance_retaliation')::text AS wi_grievance_retaliation,
    (fslm.performance ->> 'wi_has_facility_ever_tried')::text AS wi_has_facility_ever_tried,
    (fslm.performance ->> 'wi_has_facility_failed_implement')::text AS wi_has_facility_failed_implement,
    (fslm.performance ->> 'wi_interferance_foa')::boolean AS wi_interferance_foa,
    (fslm.performance ->> 'wi_legally_required_mechanisms_dialogue')::text AS wi_legally_required_mechanisms_dialogue,
    (fslm.performance ->> 'wi_legally_required_workers_representatives')::text AS wi_legally_required_workers_representatives,
    (fslm.performance ->> 'wi_vietnam_has_collective_agreement')::text AS wi_vietnam_has_collective_agreement,
    (fslm.performance ->> 'wi_were_least_twothirds_meetings')::text AS wi_were_least_twothirds_meetings,
    (fslm.performance ->> 'wi_were_terminations_trade_union')::text AS wi_were_terminations_trade_union,
    (fslm.performance ->> 'wi_workers_free_form_trade')::text AS wi_workers_free_form_trade,
    (fslm.performance ->> 'wi_workers_free_join_trade')::text AS wi_workers_free_join_trade,
    (fslm.performance ->> 'wi_workers_represenatives_available')::text AS wi_workers_represenatives_available,
    (fslm.performance ->> 'wt_benefits_maintained')::boolean AS wt_benefits_maintained,
    (fslm.performance ->> 'wt_disability_accommodations')::text AS wt_disability_accommodations,
    (fslm.performance ->> 'wt_disability_retention')::text AS wt_disability_retention,
    (fslm.performance ->> 'wt_discipline_harassment')::text AS wt_discipline_harassment,
    (fslm.performance ->> 'wt_discrimination_compensation_age')::boolean AS wt_discrimination_compensation_age,
    (fslm.performance ->> 'wt_discrimination_compensation_disability')::boolean AS wt_discrimination_compensation_disability,
    (fslm.performance ->> 'wt_discrimination_compensation_familyresponsibilities')::boolean AS wt_discrimination_compensation_familyresponsibilities,
    (fslm.performance ->> 'wt_discrimination_compensation_hiv')::boolean AS wt_discrimination_compensation_hiv,
    (fslm.performance ->> 'wt_discrimination_compensation_maritalstatus')::boolean AS wt_discrimination_compensation_maritalstatus,
    (fslm.performance ->> 'wt_discrimination_compensation_nationalextraction')::boolean AS wt_discrimination_compensation_nationalextraction,
    (fslm.performance ->> 'wt_discrimination_compensation_nationality_foreignmigrant')::boolean AS wt_discrimination_compensation_nationality_foreignmigrant,
    (fslm.performance ->> 'wt_discrimination_compensation_other')::boolean AS wt_discrimination_compensation_other,
    (fslm.performance ->> 'wt_discrimination_compensation_politicalopinion')::boolean AS wt_discrimination_compensation_politicalopinion,
    (fslm.performance ->> 'wt_discrimination_compensation_pregnancy')::boolean AS wt_discrimination_compensation_pregnancy,
    (fslm.performance ->> 'wt_discrimination_compensation_race')::boolean AS wt_discrimination_compensation_race,
    (fslm.performance ->> 'wt_discrimination_compensation_religion')::boolean AS wt_discrimination_compensation_religion,
    (fslm.performance ->> 'wt_discrimination_compensation_sex')::boolean AS wt_discrimination_compensation_sex,
    (fslm.performance ->> 'wt_discrimination_compensation_sexualorientation')::boolean AS wt_discrimination_compensation_sexualorientation,
    (fslm.performance ->> 'wt_discrimination_compensation_socialorigin')::boolean AS wt_discrimination_compensation_socialorigin,
    (fslm.performance ->> 'wt_employer_use_other_coercive')::text AS wt_employer_use_other_coercive,
    (fslm.performance ->> 'wt_employment_status_maintained')::boolean AS wt_employment_status_maintained,
    (fslm.performance ->> 'wt_facility_failing_comply_legal')::text AS wt_facility_failing_comply_legal,
    (fslm.performance ->> 'wt_facility_failing_comply_legal_other')::text AS wt_facility_failing_comply_legal_other,
    (fslm.performance ->> 'wt_facility_line_legal_requirements')::text AS wt_facility_line_legal_requirements,
    (fslm.performance ->> 'wt_facility_requires_pregnancy_tests')::boolean AS wt_facility_requires_pregnancy_tests,
    (fslm.performance ->> 'wt_facility_retain_disabled_ill')::text AS wt_facility_retain_disabled_ill,
    (fslm.performance ->> 'wt_facility_retain_ill_legal')::text AS wt_facility_retain_ill_legal,
    (fslm.performance ->> 'wt_failure_to_comply_amediated_agreements')::boolean AS wt_failure_to_comply_amediated_agreements,
    (fslm.performance ->> 'wt_failure_to_comply_arbitration')::boolean AS wt_failure_to_comply_arbitration,
    (fslm.performance ->> 'wt_failure_to_comply_court_order')::boolean AS wt_failure_to_comply_court_order,
    (fslm.performance ->> 'wt_failure_to_comply_legal_settlements')::text AS wt_failure_to_comply_legal_settlements,
    (fslm.performance ->> 'wt_failure_to_comply_settlements')::boolean AS wt_failure_to_comply_settlements,
    (fslm.performance ->> 'wt_family_responsibilities_harassment')::boolean AS wt_family_responsibilities_harassment,
    (fslm.performance ->> 'wt_family_responsibilities_promotion')::boolean AS wt_family_responsibilities_promotion,
    (fslm.performance ->> 'wt_gender_identity')::boolean AS wt_gender_identity,
    (fslm.performance ->> 'wt_harassment_other_legal_requirements')::text AS wt_harassment_other_legal_requirements,
    (fslm.performance ->> 'wt_illness_tests_legal')::text AS wt_illness_tests_legal,
    (fslm.performance ->> 'wt_marital_status')::boolean AS wt_marital_status,
    (fslm.performance ->> 'wt_national_extraction')::boolean AS wt_national_extraction,
    (fslm.performance ->> 'wt_pakistan_coc_harassment')::text AS wt_pakistan_coc_harassment,
    (fslm.performance ->> 'wt_pakistan_has_employer_set')::text AS wt_pakistan_has_employer_set,
    (fslm.performance ->> 'wt_political_opinion_harassment')::text AS wt_political_opinion_harassment,
    (fslm.performance ->> 'wt_position_maintained')::boolean AS wt_position_maintained,
    (fslm.performance ->> 'wt_retain_hiv')::text AS wt_retain_hiv,
    (fslm.performance ->> 'wt_social_origin_harassment')::boolean AS wt_social_origin_harassment,
    (fslm.performance ->> 'wt_there_been_cases_sexual')::text AS wt_there_been_cases_sexual,
    (fslm.performance ->> 'wt_vietnam_sa_training')::text AS wt_vietnam_sa_training,
    (fslm.performance ->> 'wt_wages_maintained')::boolean AS wt_wages_maintained,
    (fslm.performance ->> 'wt_workers_free_come_go')::text AS wt_workers_free_come_go,
    (fslm.performance ->> 'wt_written_contract_migrant_workers')::text AS wt_written_contract_migrant_workers
FROM fslm_simple AS fslm
INNER JOIN fslm_shares AS s
ON s.assessment_id = fslm.assessment_id
WHERE s.account_id = '6895ce2c62ff95b4065cb500' -- 1600 Test Account
)

SELECT
    account_id,
    assessment_id,
    survey_version,
(
  SELECT count(*)
  FROM unnest(ARRAY[
    cl_age_verification='No',
    cl_hazardous_work_legal IS TRUE,
    cl_healthchecks='No',
    cl_healthchecks_legal='No',
    cl_hs_protective_restrictions='No',
    cl_hs_separate_trainings='No',
    cl_hs_specialtrainings='No',
    cl_implement_separate_tracking='No',
    cl_internship_legal='No',
    cl_nightwork IS TRUE,
    cl_parental_permission='No',
    cl_parental_review='No',
    cl_protectiverestriction_u18='No',
    cl_written_remediation_policy='No',
    cl_youngest_worker IN ('Under 12','12','13','14'),
    disc_contraception_hiring IS TRUE,
    disc_contraception_requirement_employment IS TRUE,
    disc_disabled_hiring_legal='No',
    disc_illness_termination='Yes',
    disc_pregnancy_requirements_hiring IS TRUE,
    disc_promotion_age IS TRUE,
    disc_promotion_disability IS TRUE,
    disc_promotion_hiv IS TRUE,
    disc_promotion_maritalstatus IS TRUE,
    disc_promotion_maternity IS TRUE,
    disc_promotion_nationalextraction IS TRUE,
    disc_promotion_nationality IS TRUE,
    disc_promotion_other IS TRUE,
    disc_promotion_politicalopinion IS TRUE,
    disc_promotion_race IS TRUE,
    disc_promotion_religion IS TRUE,
    disc_promotion_sex IS TRUE,
    disc_promotion_sexualorientation IS TRUE,
    disc_promotion_socialorigin IS TRUE,
    disc_retaliation_termination='Yes',
    disc_termination_age IS TRUE,
    disc_termination_disability IS TRUE,
    disc_termination_hiv IS TRUE,
    disc_termination_maritalstatus IS TRUE,
    disc_termination_maternity IS TRUE,
    disc_termination_nationalextraction IS TRUE,
    disc_termination_nationality IS TRUE,
    disc_termination_other IS TRUE,
    disc_termination_politicalopinion IS TRUE,
    disc_termination_race IS TRUE,
    disc_termination_religion IS TRUE,
    disc_termination_sex IS TRUE,
    disc_termination_sexualorientation IS TRUE,
    disc_termination_socialorigin IS TRUE,
    disc_virginity_test_hiring IS TRUE,
    discp_legal='No',
    ep_defense='X',
    ep_limits_fixed_contracts='No',
    ep_personnelfiles_legal='No',
    ep_probation_legal='No',
    ep_rif_alternatives='No',
    ep_temp_contracts_avoid_legal='Yes',
    ep_work_legal='No',
    ep_workers_were_not_given_notice='X',
    erg_retaliation='Yes',
    fl_forced_overtime='Yes',
    fl_migrant_recruitment_legal='No',
    fl_passport_access='Yes',
    fl_prison_labor='Yes',
    fl_recruitment_costs_legal='No',
    fl_reimbursement_fees='No',
    fl_restricted_leaving='Yes',
    fl_terminate_employment_postnotice='No',
    fl_witheld_payments='Yes',
    foa_armed_break_strike IS TRUE,
    foa_cba_favorable_as_law='No',
    foa_consultation_union_legal='No',
    foa_control_unions='Yes',
    foa_equal_union_treatment_legal='No',
    foa_form_join_federations='No',
    foa_free_to_meet_wo_mgmt='No',
    foa_new_workers_replace_strikers IS TRUE,
    foa_private_meeting_legal='No',
    foa_punished_strikes IS TRUE,
    foa_required_union='Yes',
    foa_trade_union_representatives_access='No',
    foa_union_activity_hiring='Yes',
    foa_union_intimidation IS TRUE,
    foa_union_punished IS TRUE,
    foa_union_support_legal='No',
    foa_union_terminated IS TRUE,
    foa_unions='No',
    foa_untion_deductions_legal='No',
    hb_cases_abuse='Yes',
    hb_cases_characteristics='Yes',
    hb_effective_remediation='No',
    hb_forced_work_strike='Yes',
    hb_harassment_age IS TRUE,
    hb_harassment_disability IS TRUE,
    hb_harassment_hiv IS TRUE,
    hb_harassment_maternitystatus IS TRUE,
    hb_harassment_nationality IS TRUE,
    hb_harassment_other IS TRUE,
    hb_harassment_politicalopinion IS TRUE,
    hb_harassment_race IS TRUE,
    hb_harassment_religion IS TRUE,
    hb_harassment_sexualorientation IS TRUE,
    hb_immigration_threats='Yes',
    hb_violence_intimidation='Yes',
    hb_written_recrods_threats_forcedwork='No',
    hb_writtenrecords_discp_forcedwork='No',
    hb_writtenrecords_harassment_sexualharassment='No',
    hs_accident_rootcause='No',
    hs_air_quality='No',
    hs_airborne_particulates_legal_exposure='No',
    hs_alarm_system_all_emergencies='No',
    hs_alarm_system_no_backup IS TRUE,
    hs_alarm_system_no_maintenance IS TRUE,
    hs_alarm_system_not_accessible IS TRUE,
    hs_alarm_system_not_distinct IS TRUE,
    hs_alarm_system_not_heard IS TRUE,
    hs_alarm_system_notfunctioning IS TRUE,
    hs_are_pregnant_and_nursing='No',
    hs_bangladesh_acid_storage_legal='No',
    hs_bangladesh_overcrowding_legal_compliance='No',
    hs_building_construction_structural_legal='No',
    hs_cambodia_chemical_mixing='No',
    hs_cambodia_spills_legal='No',
    hs_cases_physical_integrity='Yes',
    hs_chemical_harardous_legal='Yes',
    hs_chemical_practices_legal='No',
    hs_chemical_shower_equipment='No',
    hs_chemicals_disposed_in_waste IS TRUE,
    hs_chemicals_inappropriate_containers IS TRUE,
    hs_chemicals_legal='No',
    hs_chemicals_no_spill_kit IS TRUE,
    hs_chemicals_no_written_procedures IS TRUE,
    hs_chemicals_other='Yes',
    hs_children_production_area='Yes',
    hs_comply_health_legal_requirements_hiv='No',
    hs_confined_authorized_entry_only IS TRUE,
    hs_confined_space_accidental_entry IS TRUE,
    hs_confined_space_air_safety='X',
    hs_confined_space_appropriate_measures='X',
    hs_confined_space_no_rescue_equip IS TRUE,
    hs_confined_space_no_signs IS TRUE,
    hs_confined_space_not_trained='X',
    hs_construction_permits_dorms='No',
    hs_contract_dispose_hazardous_waste='No',
    hs_cooperation_mechanisms_workers_management='No',
    hs_does_the_facility_record='No',
    hs_dorm_airtight_legal='X',
    hs_dorm_cooking_legal='X',
    hs_dorm_emergencyprep_legal='X',
    hs_dorm_fire_legal='X',
    hs_dorm_lighting_legal='X',
    hs_dorm_noise_legal='X',
    (hs_dorm_permits_legal='Do not know. Have not requested records from 3rd party'
    OR hs_dorm_permits_legal='No'),
    hs_dorm_pests_legal='X',
    hs_dorm_ventilation_legal='X',
    hs_dorm_wastewater_legal='X',
    hs_dorm_water_legal='X',
    hs_dormitories_space_dimensions_legal='X',
    hs_dorms_legal='No',
    hs_electrical_equipment_inspection_legal='No',
    hs_electrical_maintenance='Yes',
    hs_elevators_elevatordoors_inoperable IS TRUE,
    hs_elevators_inspection IS TRUE,
    hs_elevators_legal='No',
    hs_elevators_loadcapacity IS TRUE,
    hs_elevators_safety_devices IS TRUE,
    hs_elevators_warning_signs IS TRUE,
    hs_emergency_alarm_legal='No',
    hs_emergency_drills='No',
    hs_emergency_exit_doors IS TRUE,
    hs_emergency_exits_marked='No',
    hs_emergency_exits_safe='No',
    hs_emergency_response_vehicles='No',
    hs_emergencyexits_legal='No',
    hs_ergonomics='No',
    hs_evacuation_legal='No',
    hs_evacuationplans_legal='No',
    hs_facility_provides_drinking_water='No',
    hs_facilitydoors_legal='No',
    hs_fallprotection_designated_location IS TRUE,
    hs_fallprotection_maintenance_logs IS TRUE,
    hs_fallprotection_not_trained IS TRUE,
    hs_fallprotection_not_worn_at_all_times IS TRUE,
    hs_fallprotection_notgoodcondition IS TRUE,
    hs_fallprotection_notusing IS TRUE,
    hs_fallprotection_nowalls IS TRUE,
    hs_fallprotection_training_logs IS TRUE,
    hs_fire_alarms_legal='No',
    hs_fire_detection_legal='No',
    hs_fire_training='No',
    hs_firefighting_equipment_legal='No',
    hs_firefighting_equipment_not_accessible IS TRUE,
    hs_firefighting_non IS NULL,
    hs_firefighting_not_marked IS TRUE,
    hs_firefighting_training_legal='No',
    hs_first_aid_kits_not_accessible='X',
    hs_first_aid_kits_not_maintained='X',
    hs_first_aid_kits_not_sufficient='X',
    hs_flammable_materials_not_stored_safely='No',
    hs_foodservice_permits_legal='No',
    hs_free_drinking_water='No',
    hs_fuel_storage_legal='No',
    hs_ghs_available='No',
    hs_hazardous_substances_exposure='Yes',
    hs_hazardous_substances_exposure_label='No',
    hs_hazardous_substances_legal='No',
    hs_hazardous_work_monitoring_legal='No',
    hs_health_safety_risk_assessment_conducted='No',
    hs_hot_work_legal='No',
    hs_hs_assessment='No',
    hs_ignition_sources_not_safeguarded='No',
    hs_initial_and_refresher_trainings_firefighting IS TRUE,
    hs_inventory_hazardous_substances='No',
    hs_laser_radiation_legal='No',
    hs_legal_equipment_eyewash='No',
    hs_legally_required_facilities_provided='No',
    hs_lighting_legal='No',
    hs_lightning_protector_legal='No',
    hs_machinery_maintenance_of_worker_machinery IS TRUE,
    hs_machinery_no_instructions_language IS TRUE,
    hs_medical_checks_legal='No',
    hs_medical_emergency_arrangements='No',
    hs_negative_consequences_removing_dangerous_situation='Yes',
    hs_no_automatic_and_centralized IS TRUE,
    hs_no_back_up_battery_ee_lighting IS TRUE,
    hs_no_equipment_firefighting IS TRUE,
    hs_no_fire_resistant_walls IS TRUE,
    hs_no_first_aid_records='X',
    hs_no_first_aid_training='X',
    hs_no_functioning_lockout_or_tagout='X',
    hs_no_illumination_ee IS TRUE,
    hs_no_marking_nor_exit IS TRUE,
    hs_noise_exposure_legal_compliance='No',
    hs_noise_level_legal='No',
    hs_noise_testing='No',
    hs_non_prod_hs_noncompliance='Yes',
    hs_off_site_canteens_legal='No',
    hs_onsite_canteens_legal='No',
    hs_onsite_childcare_legal='No',
    hs_osh_committee_formed_and_functioning='No',
    hs_osh_committee_wo_legal='No',
    hs_osh_cost_to_workers='Yes',
    hs_other_health_safety_legal_noncompliance='Yes',
    hs_outlets_wet_area='No',
    hs_pcb='No',
    hs_ppe_for_dmf='No',
    hs_ppe_for_dmf_condition='No',
    hs_ppe_for_perc='No',
    hs_ppe_for_perc_condition='No',
    hs_ppe_for_pp='No',
    hs_ppe_for_pp_condition='No',
    hs_ppe_training_legal='No',
    hs_prevent_floor_opening='X',
    hs_prevent_slips='X',
    hs_prevent_standing_water='X',
    hs_provided_ppe_legal='No',
    hs_qualified_osh_staff_legal_requirement='No',
    hs_required_guards_legal='No',
    hs_required_training_free='No',
    hs_safety_warnings_legally_posted='No',
    hs_sanitation_practices_legal_compliance='No',
    hs_sufficient_emergency='No',
    hs_sufficient_toilets_legal='No',
    hs_sustation_legal='No',
    hs_temperature_ventilation_legal_compliance='No',
    hs_tempsystems_legal='No',
    hs_test_fire_alarms='No',
    hs_toilets_legal_requirements_met='No',
    hs_training_records_chemical_12months IS TRUE,
    hs_vietnam_annual_osh_plan='No',
    hs_vietnam_environmental_conditions_monitoring='No',
    hs_vietnam_maintenance_machinery_legal='No',
    hs_vietnam_occupational_health_legal='No',
    hs_waste_discharge_permits='No',
    hs_waste_disposal_legal_compliance='No',
    hs_worker_access_drinking_water_anytime='No',
    hs_worker_access_toilets_anytime='No',
    hs_written_osh_policy_legal_compliance='No',
    rh_age_jd='X',
    rh_age_referenced='X',
    rh_bangladesh_do_all_workers='No',
    rh_cambodia_entitlements_legal='No',
    rh_child_labor_hours_exceeded IS TRUE,
    rh_child_labor_legal_noncompliance='Yes',
    rh_child_worker_registry='No',
    rh_contract_practices_legal='Yes',
    rh_contract_practices_nonprod_legal='Yes',
    rh_contracts_do_not_clearly IS TRUE,
    rh_copies_of_contracts_are='X',
    rh_disability_referenced='X',
    rh_discrimination_noncompliance='Yes',
    rh_family_responsibilities='Yes',
    rh_family_responsibilities_hiring='X',
    rh_family_responsibilities_jd='X',
    rh_forced_labor_underage='Yes',
    rh_hiv_status_hiring='X',
    rh_hiv_status_referenced='X',
    rh_hiv_testing_jd='No',
    rh_homeworkers_legal='No',
    rh_illness_testing_hiring_legal='No',
    rh_indonesia_outsourced_legal='No',
    rh_job_application_discrimination='Yes',
    rh_job_description_discrimination='X',
    rh_marital_status_hiring='X',
    rh_marital_status_referenced='X',
    rh_migrant_contracts_legal='No',
    rh_monetary_deposits_legal='Yes',
    rh_national_extraction_hiring IS TRUE,
    rh_national_extraction_referenced IS TRUE,
    rh_nationality_jd='X',
    rh_nationality_referenced='X',
    rh_other_identified_jd='X',
    rh_political_opinion_hiring IS TRUE,
    rh_political_opinion_referenced IS TRUE,
    rh_pregnancy_hiring IS TRUE,
    rh_pregnancy_referenced IS TRUE,
    rh_pregnancy_testing IS TRUE,
    rh_prison_laborers_have_not IS TRUE,
    rh_race_ethnic_group_skin IS TRUE,
    rh_race_ethnic_group_skin_jd IS TRUE,
    rh_religion_hiring IS TRUE,
    rh_religion_referenced_hiring IS TRUE,
    rh_sex_gender_hiring IS TRUE,
    rh_sex_gender_jd IS TRUE,
    rh_sexual_orientation_hiring='X',
    rh_sexual_orientation_referenced='X',
    rh_signed_copies_of_contracts IS TRUE,
    rh_social_origin_hiring IS TRUE,
    rh_social_origin_referenced IS TRUE,
    rh_the_facility_does_not IS TRUE,
    rh_there_is_no_supervision IS TRUE,
    rh_vietnam_disability_legal='No',
    rh_worker_privacy='No',
    rh_workplace_legal='No',
    ter_debt_bondage_risk='No',
    ter_family_responsibilities IS TRUE,
    ter_invalid_termination_reasons='X',
    ter_legal_compliance='Yes',
    ter_other_discrimination='Yes',
    ter_race_ethnic_group='Yes',
    ter_reinstatement_orders_not_followed IS TRUE,
    ter_severance_not_paid='X',
    ter_suspension_legal_compliance='No',
    ter_termination_benefits_not_paid='X',
    ter_termination_noncompliance_general='Yes',
    ter_termination_nonprod_noncompliance='Yes',
    ter_termination_payment_delay='X',
    ter_unused_leave_not_paid='X',
    wb_accurate_detailed_payslips='No',
    (wb_agencycontract_workers='Unable to assess' OR
    wb_agencycontract_workers='X'),
    wb_annual_leave_failing_to_pay IS TRUE,
    wb_authorized_3rd_party_agents='No',
    wb_bangladesh_has_facility_established='No',
    wb_bangladesh_workers_participation_welfare='No',
    wb_cambodia_attendance_bonus_casual IS TRUE,
    wb_cambodia_attendance_bonus_during IS TRUE,
    wb_cambodia_attendance_bonus_new IS TRUE,
    wb_cambodia_piece_rate_set='No',
    wb_cambodia_seniority_indemnity_undetermined IS TRUE,
    wb_cambodia_transport_home_place IS TRUE,
    wb_cambodia_wage_supplements_including IS TRUE,
    wb_casual_workers='X',
    wb_compensation_workers_death IS TRUE,
    wb_compensation_workrelated_accidents_diseases IS TRUE,
    wb_compensatorytimeoff_legal='No',
    wb_compulsory_group_insurance_workers IS TRUE,
    wb_confirm_accuracy_writing='No',
    (wb_contract_workers_who_part='Unable to assess' OR
    wb_contract_workers_who_part='X'),
    wb_deductions_injury='X',
    wb_deductions_maternity='X',
    wb_deductions_medical='X',
    wb_deductions_unemployment='X',
    wb_deductions_voluntarily_accepted_workers IS TRUE,
    wb_deductions_wages_explained_workers IS TRUE,
    wb_dispute_correct_wages='No',
    wb_ethiopia_correct_time_off IS NULL,
    wb_ethiopia_provide_legally_required IS NULL,
    wb_ethiopia_provide_prenatal IS NULL,
    wb_ethiopia_provide_time_off IS NULL,
    wb_facility_comply_leave_legal='No',
    wb_facility_conduct_worker_performance='No',
    wb_facility_failing_comply_legal='Yes',
    wb_facility_failing_correctly_provide='Yes',
    wb_facility_failing_leave_legal_other='Yes',
    wb_facility_failing_pay_worker_basicwage='Yes',
    wb_facility_failing_pay_worker_cba='Yes',
    wb_facility_failing_pay_worker_legalmin='Yes',
    wb_facility_failing_pay_workers_experience='Yes',
    wb_facility_failing_pay_workers_overtime='Yes',
    wb_facility_failing_pay_workers_overtime_legal='Yes',
    wb_facility_failing_pay_workers_regular='Yes',
    wb_facility_has_overdue_social='No',
    wb_facility_paid_annual_bonus='No- out of line with legal requirements',
    wb_facility_paid_attendance_bonus='No- out of line with legal requirements',
    wb_facility_paid_housing_allowance='No- out of line with legal requirements',
    wb_facility_paid_meal_allowance='No- out of line with legal requirements',
    wb_facility_paid_productivity_bonus='No- out of line with legal requirements',
    wb_facility_paid_seniority_andor='No- out of line with legal requirements',
    wb_facility_paid_transportation_allowance='No- out of line with legal requirements',
    wb_facility_pay_workers_correctly='No',
    wb_facility_provide_legally_required='No',
    wb_facility_provide_other_insurance='No',
    wb_facility_register_workers_social='No',
    wb_facility_take_deductions_wages='Yes',
    wb_failing_topay_leave='Yes',
    wb_failing_topay_overtime_night IS TRUE,
    wb_failing_topay_overtime_ordinary IS TRUE,
    wb_failing_topay_overtime_public_holidays IS TRUE,
    wb_failing_topay_overtime_weekly_restdays IS TRUE,
    wb_indonesia_facility_comply_legal='No',
    wb_indonesia_facility_comply_requirements='No',
    wb_indonesia_facility_establish_wage='No',
    wb_indonesia_nationalhealthcare='No',
    wb_inkind_benefits_legal='No',
    wb_loans_legal='No',
    wb_maternity_collected_forwarded='X',
    wb_maternity_leave_failing_to_pay IS TRUE,
    wb_medical_collected_forwarded='X',
    wb_one_payroll_record='No',
    wb_other IS TRUE,
    wb_other_collected_forwarded='X',
    wb_other_monetary_bonuses_andor='No- out of line with legal requirements',
    wb_other_types_required_leave_failing_to_pay IS TRUE,
    wb_overtime_allowances_providedpaid_line='No',
    wb_overtime_premium='No',
    wb_pakistan_employer_maintain_fair='Yes',
    wb_pakistan_facility_pay_workers='No',
    wb_pakistan_iddat_leave IS NULL,
    wb_pakistan_workers_receive_correct='No',
    wb_pakistan_workers_survivors_benefit='No',
    wb_pakistan_workers_survivors_injury='No',
    wb_pakistan_workers_survivors_medical='No',
    wb_parttime_workers_failing_timeoff='X',
    wb_paternity_leave_failing_to_pay IS TRUE,
    wb_payroll_records_consistent_attendance IS TRUE,
    wb_payroll_records_each_worker IS TRUE,
    wb_payroll_records_show_types='X',
    wb_pension_provident_fund_collected='X',
    wb_pension_provident_fund_collected_legal='X',
    wb_permanent_workers='X',
    wb_personal_leave_failing_to_pay IS TRUE,
    wb_piece_rate_workers_paid='No',
    wb_premiumpay_night='X',
    wb_premiumpay_public_holidays='X',
    wb_premiumpay_weeklyrestdays='X',
    wb_public_holidays_failing_to_pay IS TRUE,
    wb_sick_leave_failing_to_pay IS TRUE,
    wb_temporary_workers='X',
    wb_unemployment_collected_forwarded='X',
    wb_vietnam_facility_collect_forward='No',
    wb_vietnam_facility_comply_applicable='No',
    wb_vietnam_facility_contribution_social IS NULL,
    wb_vietnam_facility_incorporate_legally='No',
    wb_vietnam_facility_submit_claims='No',
    wb_vietnam_provide_period_break IS NULL,
    wb_vietnam_failing_to_pay_period_leave IS NULL,
    wb_wage_basis_legal_requirements IS NULL,
    wb_wage_payments_made_regularly='No',
    wb_were_other_wage_payments='No',
    wb_were_withholdings_wages_other='No',
    wb_workers_access_account_status IS TRUE,
    wb_workers_give_written_consent IS TRUE,
    wb_workers_informed_about_individual='No',
    wb_workers_paid_full_wages='No',
    wb_workers_paid_workrelated_activities='No',
    wb_workers_under_probation='X',
    wb_workers_were_paid_correctly='X',
    wb_workers_who_trainees_apprentices='X',
    wb_workrelated_injury_illness_death='X',
    wb_written_terms_legal='No',
    wh_breastfeeding_legal='No',
    wh_exceed_legal_requirements='Yes',
    wh_facility_failing_comply_legal_nonprod='Yes',
    wh_facility_failing_comply_legal_other='Yes',
    wh_facility_maintain_only_one='No',
    wh_facility_only_require_workers='No',
    wh_facility_provide_breaks_during='No',
    wh_govt_permission_legal='No',
    wh_no_impact_workers_workers IS NULL,
    wh_other_action_impacting_workers IS TRUE,
    wh_overtime_voluntary_line_legal='No',
    wh_overtime_working_hours_line='No',
    wh_pakistan_provide_required_time IS NULL,
    wh_reasons_overtime_line_legal='No',
    wh_vietnam_facility_comply_legal='No',
    wh_weeklyrestdays_legal='No',
    wh_work_targets_production_eg='No',
    wh_records_kept_12m IS TRUE,
    wh_workers_hours_reduced IS TRUE,
    wh_workers_must_stay_home_less_minwage IS TRUE,
    wh_workers_must_stay_home_minwage IS NULL,
    wh_workers_must_stay_home_notpaid IS TRUE,
    wh_workers_must_stay_home_pto IS TRUE,
    wh_yes_regular_hours_exceed='Yes',
    wi_bangladesh_facility_legally_required='No',
    wi_bipartite_committees_established_functioning='No',
    wi_employer_allow_workers_carry='No',
    wi_facility_failing_comply_legal='Yes',
    wi_facility_has_no_trade='No',
    wi_facility_inform_workers_about='No',
    wi_facility_refuse_bargain_collectively='Yes',
    wi_grievance_retaliation='No',
    wi_has_facility_ever_tried='Yes',
    wi_has_facility_failed_implement='Yes',
    wi_interferance_foa IS NULL,
    wi_legally_required_mechanisms_dialogue='No',
    wi_legally_required_workers_representatives='No',
    wi_vietnam_has_collective_agreement='No',
    wi_were_least_twothirds_meetings='No',
    wi_were_terminations_trade_union='No',
    wi_workers_free_form_trade='No',
    wi_workers_free_join_trade='No',
    wi_workers_represenatives_available='No',
    wt_benefits_maintained IS TRUE,
    wt_disability_accommodations='No',
    wt_disability_retention='No',
    wt_discipline_harassment='Yes',
    wt_discrimination_compensation_age IS TRUE,
    wt_discrimination_compensation_disability IS TRUE,
    wt_discrimination_compensation_familyresponsibilities IS TRUE,
    wt_discrimination_compensation_hiv IS TRUE,
    wt_discrimination_compensation_maritalstatus IS TRUE,
    wt_discrimination_compensation_nationalextraction IS TRUE,
    wt_discrimination_compensation_nationality_foreignmigrant IS TRUE,
    wt_discrimination_compensation_other IS TRUE,
    wt_discrimination_compensation_politicalopinion IS TRUE,
    wt_discrimination_compensation_pregnancy IS TRUE,
    wt_discrimination_compensation_race IS TRUE,
    wt_discrimination_compensation_religion IS TRUE,
    wt_discrimination_compensation_sex IS TRUE,
    wt_discrimination_compensation_sexualorientation IS TRUE,
    wt_discrimination_compensation_socialorigin IS TRUE,
    wt_employer_use_other_coercive='Yes',
    wt_employment_status_maintained IS TRUE,
    wt_facility_failing_comply_legal='Yes',
    wt_facility_failing_comply_legal_other='Yes',
    wt_facility_line_legal_requirements='No',
    wt_facility_requires_pregnancy_tests IS TRUE,
    wt_facility_retain_disabled_ill='No',
    wt_facility_retain_ill_legal='No',
    wt_failure_to_comply_amediated_agreements IS TRUE,
    wt_failure_to_comply_arbitration IS TRUE,
    wt_failure_to_comply_court_order IS TRUE,
    wt_failure_to_comply_legal_settlements='Yes',
    wt_failure_to_comply_settlements IS TRUE,
    wt_family_responsibilities_harassment IS TRUE,
    wt_family_responsibilities_promotion IS TRUE,
    wt_gender_identity IS TRUE,
    wt_harassment_other_legal_requirements='Yes',
    wt_illness_tests_legal='No',
    wt_marital_status IS TRUE,
    wt_national_extraction IS TRUE,
    wt_pakistan_coc_harassment='No',
    wt_pakistan_has_employer_set='No',
    wt_political_opinion_harassment='No',
    wt_position_maintained IS TRUE,
    wt_retain_hiv='No',
    wt_social_origin_harassment IS TRUE,
    wt_there_been_cases_sexual='Yes',
    wt_vietnam_sa_training='No',
    wt_wages_maintained IS TRUE,
    wt_workers_free_come_go='No',
    wt_written_contract_migrant_workers='No'
 ]) AS t(x)
  WHERE x IS TRUE
) AS all_flag_count
FROM fslm_cte
LIMIT 100