DROP TABLE IF EXISTS isaac_hopwood.waste_disposal;

CREATE TABLE isaac_hopwood.waste_disposal AS

SELECT
    assessment_id,
	status,
	rfi_pid,
    answers -> 'wstsourcenhtextiledisposal' AS textile_method,
    jsonb_array_length(answers -> 'wstsourcenhtextiledisposal') AS textile_method_count,
    CAST(calculations ->> 'wstsourcenhtextilequant_kg' AS numeric) AS textile_quant_kg,
    answers -> 'wstsourcenhleatherdisposal' AS leather_method,
    jsonb_array_length(answers -> 'wstsourcenhleatherdisposal') AS leather_method_count,
    CAST(calculations ->> 'wstsourcenhleatherquant_kg' AS numeric) AS leather_quant_kg,
    answers -> 'wstsourcenhrubberdisposal' AS rubber_method,
    jsonb_array_length(answers -> 'wstsourcenhrubberdisposal') AS rubber_method_count,
    CAST(calculations ->> 'wstsourcenhrubberquant_kg' AS numeric) AS rubber_quant_kg,
    answers -> 'wstsourcenhmetaldisposal' AS metal_method,
    jsonb_array_length(answers -> 'wstsourcenhmetaldisposal') AS metal_method_count,
    CAST(calculations ->> 'wstsourcenhmetalquant_kg' AS numeric) AS metal_quant_kg,
    answers -> 'wstsourcenhplasticdisposal' AS plastic_method,
    jsonb_array_length(answers -> 'wstsourcenhplasticdisposal') AS plastic_method_count,
    CAST(calculations ->> 'wstsourcenhplasticquant_kg' AS numeric) AS plastic_quant_kg,
    answers -> 'wstsourcenhpaperdisposal' AS paper_method,
    jsonb_array_length(answers -> 'wstsourcenhpaperdisposal') AS paper_method_count,
    CAST(calculations ->> 'wstsourcenhpaperquant_kg' AS numeric) AS paper_quant_kg,
    answers -> 'wstsourcenhcansdisposal' AS cans_method,
    jsonb_array_length(answers -> 'wstsourcenhcansdisposal') AS cans_method_count,
    CAST(calculations ->> 'wstsourcenhcansquant_kg' AS numeric) AS cans_quant_kg,
    answers -> 'wstsourcenhwooddisposal' AS wood_method,
    jsonb_array_length(answers -> 'wstsourcenhwooddisposal') AS wood_method_count,
    CAST(calculations ->> 'wstsourcenhwoodquant_kg' AS numeric) AS wood_quant_kg,
    answers -> 'wstsourcenhfooddisposal' AS food_method,
    jsonb_array_length(answers -> 'wstsourcenhfooddisposal') AS food_method_count,
    CAST(calculations ->> 'wstsourcenhfoodquant_kg' AS numeric) AS food_quant_kg,
    answers -> 'wstsourcenhglassdisposal' AS glass_method,
    jsonb_array_length(answers -> 'wstsourcenhglassdisposal') AS glass_method_count,
    CAST(calculations ->> 'wstsourcenhglassquant_kg' AS numeric) AS glass_quant_kg,
    answers -> 'wstsourcenhcartonsdisposal' AS cartons_method,
    jsonb_array_length(answers -> 'wstsourcenhcartonsdisposal') AS cartons_method_count,
    CAST(calculations ->> 'wstsourcenhcartonsquant_kg' AS numeric) AS cartons_quant_kg,
    answers -> 'wstsourcenhfoamsdisposal' AS foams_method,
    jsonb_array_length(answers -> 'wstsourcenhfoamsdisposal') AS foams_method_count,
    CAST(calculations ->> 'wstsourcenhfoamsquant_kg' AS numeric) AS foams_quant_kg,
    answers -> 'wstsourcenhwastewaterTreatmentSludgedisposal' AS wastewaterTreatmentSludge_method,
    jsonb_array_length(answers -> 'wstsourcenhwastewaterTreatmentSludgedisposal') AS wastewaterTreatmentSludge_method_count,
    CAST(calculations ->> 'wstsourcenhwastewaterTreatmentSludgequant_kg' AS numeric) AS wastewaterTreatmentSludge_quant_kg,
    answers -> 'wstsourcenhgeneraldisposal' AS nh_general_method,
    jsonb_array_length(answers -> 'wstsourcenhgeneraldisposal') AS nh_general_method_count,
    CAST(calculations ->> 'wstsourcenhgeneralquant_kg' AS numeric) AS nh_general_quant_kg,
    answers -> 'wstsourcenhslagnhdisposal' AS slag_nh_method,
    jsonb_array_length(answers -> 'wstsourcenhslagnhdisposal') AS slag_nh_method_count,
    CAST(calculations ->> 'wstsourcenhslagnhquant_kg' AS numeric) AS slag_nh_quant_kg,
    answers -> 'wstsourcenhotherdisposal' AS nh_other_method,
    jsonb_array_length(answers -> 'wstsourcenhotherdisposal') AS nh_other_method_count,
    CAST(calculations ->> 'wstsourcenhotherquant_kg' AS numeric) AS nh_other_quant_kg,
    answers -> 'wstsourcehprodchemdrumdisposal' AS prodchemdrum_method,
    jsonb_array_length(answers -> 'wstsourcehprodchemdrumdisposal') AS prodchemdrum_method_count,
    CAST(calculations ->> 'wstsourcehprodchemdrumquant_kg' AS numeric) AS prodchemdrum_quant_kg,
    answers -> 'wstsourcehprodfilmprintdisposal' AS prodfilmprint_method,
    jsonb_array_length(answers -> 'wstsourcehprodfilmprintdisposal') AS prodfilmprint_method_count,
    CAST(calculations ->> 'wstsourcehprodfilmprintquant_kg' AS numeric) AS prodfilmprint_quant_kg,
    answers -> 'wstsourcehprodsludgedisposal' AS prodsludge_method,
    jsonb_array_length(answers -> 'wstsourcehprodsludgedisposal') AS prodsludge_method_count,
    CAST(calculations ->> 'wstsourcehprodsludgequant_kg' AS numeric) AS prodsludge_quant_kg,
    answers -> 'wstsourcehprodchemdisposal' AS prodchem_method,
    jsonb_array_length(answers -> 'wstsourcehprodchemdisposal') AS prodchem_method_count,
    CAST(calculations ->> 'wstsourcehprodchemquant_kg' AS numeric) AS prodchem_quant_kg,
    answers -> 'wstsourcehprodcompgasdisposal' AS prodcompgas_method,
    jsonb_array_length(answers -> 'wstsourcehprodcompgasdisposal') AS prodcompgas_method_count,
    CAST(calculations ->> 'wstsourcehprodcompgasquant_kg' AS numeric) AS prodcompgas_quant_kg,
    answers -> 'wstsourcehprodcontammatdisposal' AS prodcontammat_method,
    jsonb_array_length(answers -> 'wstsourcehprodcontammatdisposal') AS prodcontammat_method_count,
    CAST(calculations ->> 'wstsourcehprodcontammatquant_kg' AS numeric) AS prodcontammat_quant_kg,
    answers -> 'wstsourcehdombatteriesdisposal' AS dombatteries_method,
    jsonb_array_length(answers -> 'wstsourcehdombatteriesdisposal') AS dombatteries_method_count,
    CAST(calculations ->> 'wstsourcehdombatteriesquant_kg' AS numeric) AS dombatteries_quant_kg,
    answers -> 'wstsourcehdomflolightdisposal' AS domflolight_method,
    jsonb_array_length(answers -> 'wstsourcehdomflolightdisposal') AS domflolight_method_count,
    CAST(calculations ->> 'wstsourcehdomflolightquant_kg' AS numeric) AS domflolight_quant_kg,
    answers -> 'wstsourcehdominkcartdisposal' AS dominkcart_method,
    jsonb_array_length(answers -> 'wstsourcehdominkcartdisposal') AS dominkcart_method_count,
    CAST(calculations ->> 'wstsourcehdominkcartquant_kg' AS numeric) AS dominkcart_quant_kg,
    answers -> 'wstsourcehdomoilgreasedisposal' AS domoilgrease_method,
    jsonb_array_length(answers -> 'wstsourcehdomoilgreasedisposal') AS domoilgrease_method_count,
    CAST(calculations ->> 'wstsourcehdomoilgreasequant_kg' AS numeric) AS domoilgrease_quant_kg,
    answers -> 'wstsourcehproductionoildisposal' AS productionoil_method,
    jsonb_array_length(answers -> 'wstsourcehproductionoildisposal') AS productionoil_method_count,
    CAST(calculations ->> 'wstsourcehproductionoilquant_kg' AS numeric) AS productionoil_quant_kg,
    answers -> 'wstsourcehmetalsludgedisposal' AS metalsludge_method,
    jsonb_array_length(answers -> 'wstsourcehmetalsludgedisposal') AS metalsludge_method_count,
    CAST(calculations ->> 'wstsourcehmetalsludgequant_kg' AS numeric) AS metalsludge_quant_kg,
    answers -> 'wstsourcehemptyotherdisposal' AS h_emptyother_method,
    jsonb_array_length(answers -> 'wstsourcehemptyotherdisposal') AS h_emptyother_method_count,
    CAST(calculations ->> 'wstsourcehemptyotherquant_kg' AS numeric) AS h_emptyother_quant_kg,
    answers -> 'wstsourcehdomelectronicdisposal' AS domelectronic_method,
    jsonb_array_length(answers -> 'wstsourcehdomelectronicdisposal') AS domelectronic_method_count,
    CAST(calculations ->> 'wstsourcehdomelectronicquant_kg' AS numeric) AS domelectronic_quant_kg,
    answers -> 'wstsourcehdomcoalcombdisposal' AS domcoalcomb_method,
    jsonb_array_length(answers -> 'wstsourcehdomcoalcombdisposal') AS domcoalcomb_method_count,
    CAST(calculations ->> 'wstsourcehdomcoalcombquant_kg' AS numeric) AS domcoalcomb_quant_kg,
    answers -> 'wstsourcehslagdisposal' AS slag_h_method,
    jsonb_array_length(answers -> 'wstsourcehslagdisposal') AS slag_h_method_count,
    CAST(calculations ->> 'wstsourcehslagquant_kg' AS numeric) AS slag_h_quant_kg,
    answers -> 'wstsourcehotherdisposal' AS h_other_method,
    jsonb_array_length(answers -> 'wstsourcehotherdisposal') AS h_other_method_count,
    CAST(calculations ->> 'wstsourcehotherquant_kg' AS numeric) AS h_other_quant_kg
FROM public.fem_simple
WHERE facility_posted = TRUE